DEV-9893 프로젝트 구조, namespace, 프로비저닝 수정
HardBoiledSmith/johanna pull request #375
Opened 2020-08-21 15:41 UTC by singetta

### What is this PR for?
- magi gendo -> BRANCH 설정에 따른 aws eb provisioning (https://github.com/HardBoiledSmith/magi/pull/643)

- 변경사항
1) gendo 프로젝트 구조, 프로비저닝 변경에 따른 aws eb 설치 진행 (https://github.com/HardBoiledSmith/gendo/pull/330)
1) gendo 중 특정 브랜치에 해당하는 코드 및 artifact 다운로드 후 aws eb에 설치 진행

2020-08-25 06:15 UTC, GoldieKMG approved these changes
고생하셨습니다

2020-08-25 06:35 UTC, rkdgusrnrlrl reviewed
@singetta // 해당 코드는 큰문제는 없어 보이기는 하는대 아래 PR 해결이 되야 같이 Merge 될 수 있어서 Request changes 로 Comment 로 남깁니다.
https://github.com/HardBoiledSmith/gendo/pull/330#pullrequestreview-474161620

2020-08-27 08:46 UTC, yoonjs2 requested changes
@singetta // DV 브랜치를 지정할수 있게 해준건 좋은 아이디어 같습니다. 다만 기존 배포 파이프라인과 호환되게 만들러면 optional 로 지정이 필요할것 같네요

2020-08-27 08:46 UTC, yoonjs2 commented on run_create_eb_windows.py
> +        git_command = ['git', 'clone', '--depth=1', '-b', sub_branch, git_url]
@singetta // DV에서만 브랜치를 선택할수 있게 해놨기 때문에 어떤 브랜치를 땡겨오는지 직전에 알려주면 좋을것 같습니다.
```suggestion
        print(f'dv branch: {dv_branch}')
        git_command = ['git', 'clone', '--depth=1', '-b', dv_branch, git_url]
```

2020-08-27 08:46 UTC, yoonjs2 commented on run_create_eb_windows.py
> +    print(f'git branch: {sub_branch}')
@singetta // https://github.com/HardBoiledSmith/magi/pull/643/files#diff-ddb889719aa075b6e5d62781865343c5R929 에 들어가는 값들은 필수 값들이 대부분이어서 이런 경우는 아래처럼 optional로 처리하는게 좋을것 같습니다. 
```suggestion
    dv_branch = settings.get('BRANCH', 'master')
```

2020-08-27 08:46 UTC, yoonjs2 commented on run_create_eb_windows.py
> +    branch = sub_branch.lower() if phase == 'dv' else phase
```suggestion
    branch = dv_branch.lower() if phase == 'dv' else phase
```

2020-08-28 06:25 UTC, singetta commented
> @singetta // DV 브랜치를 지정할수 있게 해준건 좋은 아이디어 같습니다. 다만 기존 배포 파이프라인과 호환되게 만들러면 optional 로 지정이 필요할것 같네요. 그리고 이 방법에 대해서 magi/README.md 에 설명을 추가하는게 좋을것 같습니다.

이런 방법이 있었네요. python argument로 넘기려다가 magi가 있어서 설정 시 혼란이 있을 것 같아 magi에 값 추가 했었는데 요청하신 방법대로 하면 optional로 유저 입력 유무에 따라 바꿀 수 있겠네요. 요청하신 제안 방법 적용하겠습니다.

2020-08-30 07:34 UTC, yoonjs2 approved these changes

2020-09-01 02:30 UTC, merged