DEV-9987 johanna: gendo 에 asp 서버 세팅 될 수 있도록 수정
HardBoiledSmith/johanna pull request #383
Opened 2020-09-18 06:31 UTC by GoldieKMG

### What is this PR for?
- eb gendo에 ASP 빌드 된 파일 IIS 서버 세팅

### How should this be tested?
- johanna에서 iam, vpc, client vpn, gendo 를 띄워주세요.
- gendo가 뜨면 vpn을 통해 vpc망으로 접속 후 gendo의 url로 접속해주세요.  (vpn 키는 johanna 저장소에 readme.md파일을 참고하면 됩니다)

### Screenshots (if appropriate)
johanna에서 올릴 때 이러한 구조여야 합니다.
![image](https://user-images.githubusercontent.com/42234701/93561228-c3a9a980-f9be-11ea-8d21-cc9d4152e2e8.png)
gendo-artifact.zip = gendo가 빌드 된 파일
watchdog-artifact.zip = iis서버 세팅 파일
aws-windows-deployment-manifest.json  = 겐도 시작 시 세팅 될 목록 지정 파일.

정상적으로 떳을 시 나오는 페이지.
![image](https://user-images.githubusercontent.com/42234701/93564022-f99d5c80-f9c3-11ea-9231-d3a09b817506.png)

2020-09-22 06:50 UTC, yoonjs2 requested changes
@GoldieKMG // 구현 감사합니다! 다만, 하나 Sachiel 처럼 Enhanced health reporting이 동작되는지 보고 싶은데요 
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/health-enhanced.html

아래 라인을 
https://github.com/HardBoiledSmith/johanna/pull/383/files#diff-ac81e73efe2b8d51dc380559f407d935R344-R348

이렇게 수정해서 sachiel 처럼 EB Web console 에서 확인가능한지 봐주실수 있을까요?
https://github.com/HardBoiledSmith/johanna/blob/9737d8add3d3d42833a4b4efd4522cf5cdbcde9d/run_create_eb_django.py#L329-L355

2020-09-22 08:08 UTC, GoldieKMG commented
> @GoldieKMG // 구현 감사합니다! 다만, 하나 Sachiel 처럼 Enhanced health reporting이 동작되는지 보고 싶은데요
> https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/health-enhanced.html
> 
> 아래 라인을
> https://github.com/HardBoiledSmith/johanna/pull/383/files#diff-ac81e73efe2b8d51dc380559f407d935R344-R348
> 
> 이렇게 수정해서 sachiel 처럼 EB Web console 에서 확인가능한지 봐주실수 있을까요?
> https://github.com/HardBoiledSmith/johanna/blob/9737d8add3d3d42833a4b4efd4522cf5cdbcde9d/run_create_eb_django.py#L329-L355

진행 후 전달 드리겠습니다 :)

2020-09-22 12:35 UTC, GoldieKMG commented
@yoonjs2 // 말씀하신 값으로 
`
 oo = dict() 
 oo['Namespace'] = 'aws:elasticbeanstalk:healthreporting:system' 
 oo['OptionName'] = 'SystemType' 
 oo['Value'] = 'enhanced' 
 option_settings.append(oo) 
  
 oo = dict() 
 oo['Namespace'] = 'aws:elasticbeanstalk:healthreporting:system' 
 oo['OptionName'] = 'ConfigDocument' 
 cw_env = dict() 
 cw_env['ApplicationRequestsTotal'] = 60 
 cw_env['ApplicationRequests2xx'] = 60 
 cw_env['ApplicationRequests3xx'] = 60 
 cw_env['ApplicationRequests4xx'] = 60 
 cw_env['ApplicationRequests5xx'] = 60 
 cw_instance = dict() 
 cw_instance['RootFilesystemUtil'] = 60 
 cw_instance['InstanceHealth'] = 60 
 cw_instance['CPUIdle'] = 60 
 cw = dict() 
 cw['Environment'] = cw_env 
 cw['Instance'] = cw_instance 
 cfg_doc = dict() 
 cfg_doc['CloudWatchMetrics'] = cw 
 cfg_doc['Version'] = 1 
 oo['Value'] = json.dumps(cfg_doc) 
 option_settings.append(oo) 
`
을 추가하여 진행 해 보았는데요 , 처음에 에러가나와서 알고보니 window 는  cw_instance['RootFilesystemUtil'] = 60  는 linux만 사용하는 값이라 
![image](https://user-images.githubusercontent.com/42234701/93882188-d1429480-fd1a-11ea-9662-00bd69d67c32.png)

 cw_instance = dict() 
 cw_instance['RootFilesystemUtil'] = 60 
 cw_instance['InstanceHealth'] = 60 
 cw_instance['CPUIdle'] = 60 
을 
 cw_instance = dict() 
 cw_instance['InstanceHealth'] = 60
 cw_instance['CPUIdle'] = 60
의 값으로 진행하였는데요 성능 저하 상태로 변경 되더라구요.

![image](https://user-images.githubusercontent.com/42234701/93882379-1e266b00-fd1b-11ea-9417-a33233a45545.png)

![image](https://user-images.githubusercontent.com/42234701/93882527-52019080-fd1b-11ea-8581-ad9971634688.png)
이러한 상태가 되더라구요. 제가 이 이슈에 대해서는 추가로 무언가를 작업할 시간을 배분하지 않아 만약 조사 및 수정을 생각하신다면 다음 스프린트에 이슈를 만들어 파악해야하지 않을까 합니다.

2020-09-23 04:52 UTC, GoldieKMG commented
@HardBoiledSmith/code-reviewer // @yoonjs2 님과 이야기 진행하였습니다. 코드리뷰에 대한 내용 적용은 다음 스프린트(W40/41)
후속 이슈 https://hbsmith.atlassian.net/browse/DEV-10267 로 진행 하겠습니다.

2020-09-24 05:57 UTC, yoonjs2 approved these changes
@GoldieKMG @rkdgusrnrlrl // 코드리뷰에 이야기한 Enhanced Monitoring 건 https://hbsmith.atlassian.net/browse/DEV-10267 은 W40/41에 진행하기로 하였고, DEV-9987 수정만으로는 문제가 없다고 판단하여 approve 하겠습니다.

2020-09-24 06:21 UTC, rkdgusrnrlrl approved these changes
@GoldieKMG // 시행착오가 많은 수 밖에 없는 이슈라 고생 많으셨을 것 같습니다. 고생한 만큼 피가 되고 살이 되는 경험이 되길 바라겠습니다. ㅎㅎ

2020-09-26 09:10 UTC, merged