DEV-9779 gendo auto scale in out 을 sqs 통해 할 수 있도록 작업
HardBoiledSmith/johanna pull request #384
Opened 2020-09-23 18:44 UTC by GoldieKMG

### What is this PR for?
- gendo auto scale in out 을 sqs 통해 할 수 있도록 작업 (기초 공사)
- gendo는 현재 auto scale이 default로 생성이 되고 있습니다. min max가 동일하여 실제 사용되지 않고 있는 기능입니다.

이번에 작성 된 autoscale 정책 기반은 sqs의 ApproximateNumberOfMessagesVisible 지표를 기반으로 인 아웃을 하도록 작업 하였습니다. 기초 정책에 대한 CLI는 작성이 되어 요구사항에 맞게 변경하면 될 것 같습니다.

### How should this be tested?
- aws iam, vpc, eb (gendo)를 띄워주세요.
- 자원이 모두 뜬 후 ./run_create_eb_windows_auto_scale.py 를 실행시켜 주세요.
- gendo에 정책이 잘 적용되었는지 확인해 주세요. ( ec2 패널의 autoscale 탭을 가야 볼 수 있습니다.)
- cloudwatch alarm이 등록이 잘 되었는지 확인해주세요.

### Screenshots (if appropriate)
ec2 auto-scaling 그룹 정책
![image](https://user-images.githubusercontent.com/42234701/94054516-b5bcb400-fe16-11ea-9980-ba584cb6254a.png)

cloudwatch scale in, out alarm
![image](https://user-images.githubusercontent.com/42234701/94054574-c8cf8400-fe16-11ea-9daa-bee064e9ceac.png)

2020-09-24 06:30 UTC, rkdgusrnrlrl requested changes
@GoldieKMG // run_create_eb_windows_auto_scale 함수를 run_create_eb_windows.py 파일에 통합 하고 설정에 SCALE_OUT_ADJUSTMENT, AWS_SQS_VISUAL_TEST_RESULT 있을 때 실행 시키도록 하는 것이 좋을 것 같습니다.

2020-09-24 06:44 UTC, yoonjs2 requested changes
@GoldieKMG // 명규님 난죽택 초기에 제가 이런 자료를 찾아서 공유해 드렸는데요, 혹시 여전히 이용 가능한지 검토 바랍니다. appstream 처럼 AWS autoscaling api를 이용해야 한다면 어쩔수 없지만, 가능하다면 외부 의존없이 EB 자체만으로 해결했으면 합니다. (이렇게 하면 Terminate 할때 같이 설정도 지워줘서 편리합니다.)
https://jun711.github.io/aws/aws-elastic-beanstalk-worker-auto-scaling-by-queue-size/

아래는 참고사항입니다:

- 위 문서는 worker type의 ennvironment를 대상으로 한 문서이긴 합니다.
- 우리가 쓰는건 webserver (윈도우즈는 webserver 타입밖에 사용할수 없습니다.) 입니다.
- 따라서 위 블로그 설정을 그대로 쓸수는 없고 응용을 좀 해야 합니다. 
- .ebconfig 파일에 아래 설정을 추가 https://jun711.github.io/aws/aws-elastic-beanstalk-worker-auto-scaling-by-queue-size/#2-worker-environment-config
- .ebextension에 https://jun711.github.io/aws/aws-elastic-beanstalk-worker-auto-scaling-by-queue-size/#default-worker-queue 의 설정을 추가
- 단, worker type이 아니기 때문에 QueueName을 EB에서 가져올수 없어서 Value엔 직접 큐의 이름(`<phase prefix>-visual-test-result`)이 들어가도록  johanna를 수정해야 할것 같습니다.

확인 부탁드립니다.

2020-09-25 07:28 UTC, GoldieKMG commented
@yoonjs2 // 설정 관련한 부분들은 생성된 ec2 autoscale group에 작업되는 부분이라 terminate작업 없이 eb가 정리가 되니 같이 정리가 되더라구요. 올려주신 링크 토대로 변경하여 진행해봤는데 반영은 잘 되는 것 같습니다. 단, 우려되는 점은 api를 사용해야 하는 부분들이 있을 것 같습니다.

두 가지 케이스로 진행해본 경우인데요. 차이점이 있습니다.
case 1) 기존 elb 세팅으로 올린 후 api를 이용하여 autoscale group 조정. ( run_create_eb_windows_auto_scale )
해당 케이스는 기본으로 올려진 부분에 대해서 default로 생성된 정책을 삭제 후 새로 생성하여 반영을 하는 작업입니다.
이렇게하면 최종 결과로 남는 부분은 auto scale group 안에 정책 및 cloud watch alarm(trigger)은 새로 생성한 2개 만 남게 됩니다.


case2 ) 기존 elb 에서 처음 생성될 때 바라보게끔 변경
별도로 api 및 스크립트를 실행하지 않고 gendo.config를 통하여 auto scale 그룹이까지 생성 됩니다. 
auto scale 그룹 내에 정책 2개 (up, down ) / cloudwatch alarm 4개 ( queue에 관한것 2개, cloudwatch alarm 2개) 
![image](https://user-images.githubusercontent.com/42234701/94236533-5c54a200-ff48-11ea-9738-1c4bba7313a9.png)
cloudwatch alarm에 대해서는 생성되지 않도록 하는 방법을 찾지 못하였습니다. 최선의 방법이 
trigger가 걸리지 안도록 하는게 최선이였습니다.

![image](https://user-images.githubusercontent.com/42234701/94238945-04b83580-ff4c-11ea-839c-236c14c45e29.png)

리뷰주신 방향대로 Case2 번 별도의 다른 api아닌 elb 세팅으로만 푸는 방향으로 해결했습니다.

2020-09-28 02:23 UTC, yoonjs2 commented
> @yoonjs2 // 설정 관련한 부분들은 생성된 ec2 autoscale group에 작업되는 부분이라 terminate작업 없이 eb가 정리가 되니 같이 정리가 되더라구요. 올려주신 링크 토대로 변경하여 진행해봤는데 반영은 잘 되는 것 같습니다. 단, 우려되는 점은 api를 사용해야 하는 부분들이 있을 것 같습니다.
> 
> 두 가지 케이스로 진행해본 경우인데요. 차이점이 있습니다.
> case 1) 기존 elb 세팅으로 올린 후 api를 이용하여 autoscale group 조정. ( run_create_eb_windows_auto_scale )
> 해당 케이스는 기본으로 올려진 부분에 대해서 default로 생성된 정책을 삭제 후 새로 생성하여 반영을 하는 작업입니다.
> 이렇게하면 최종 결과로 남는 부분은 auto scale group 안에 정책 및 cloud watch alarm(trigger)은 새로 생성한 2개 만 남게 됩니다.
> 
> case2 ) 기존 elb 에서 처음 생성될 때 바라보게끔 변경
> 별도로 api 및 스크립트를 실행하지 않고 gendo.config를 통하여 auto scale 그룹이까지 생성 됩니다.
> auto scale 그룹 내에 정책 2개 (up, down ) / cloudwatch alarm 4개 ( queue에 관한것 2개, cloudwatch alarm 2개)
> ![image](https://user-images.githubusercontent.com/42234701/94236533-5c54a200-ff48-11ea-9738-1c4bba7313a9.png)
> cloudwatch alarm에 대해서는 생성되지 않도록 하는 방법을 찾지 못하였습니다. 최선의 방법이
> trigger가 걸리지 안도록 하는게 최선이였습니다.
> 
> ![image](https://user-images.githubusercontent.com/42234701/94238945-04b83580-ff4c-11ea-839c-236c14c45e29.png)
> 
> 리뷰주신 방향대로 Case2 번 별도의 다른 api아닌 elb 세팅으로만 푸는 방향으로 해결했습니다.
> 
> 혹시 헷갈리실 수있을 것 같아 추가 정보가 한 가지 남겨두겠습니다
> ![image](https://user-images.githubusercontent.com/42234701/94239222-70020780-ff4c-11ea-835b-c63a6d6fc371.png)
> app console에서 보이는 capacity 관련한 trigger 부분은 App console에서 보이는건 반영이 안 됐습니다. network로 그대로 남아있게 됩니다.

@GoldieKMG // 고생하셨습니다. 기존 NetworkOut Alarm을 완전히 제거해 버릴수 있다면 좋겠지만 일단은 이정도로 하도록 하죠. 아마 나중에 다른 트리거를 걸게 되지 않을까 싶습니다. (예를들어 CPU 같은)

2020-09-28 02:23 UTC, yoonjs2 approved these changes

2020-09-28 02:23 UTC, merged