DEV-10481 Force upgrade to awscliv2
HardBoiledSmith/johanna pull request #397
Opened 2020-11-03 15:07 UTC by yoonjs2

### What is this PR for?
- AWSCLI v2룰 사용하도록 합니다. (v1은 강제로 삭제합니다)

### How should this be tested?
- `aws --version`으로 아래와 같이 버전이 찍히는지 확인합니다.
```
aws-cli/2.0.61 Python/3.7.3 Linux/4.14.200-155.322.amzn2.x86_64 exe/x86_64.amzn.2
```
- johanna의 주요 기능이 정상 동작하는지 확인합니다.

2020-11-05 07:47 UTC, GoldieKMG requested changes
환경을 iam , vpc를 띄우는 작업을 했었습니다. vpc를 띄우는 과정에서 
`aws ec2 import-key-pair --key-name dv-danny-xxxxx --public-key-material XX~XX` 명령어를 실행하는 과정에서 아래와 같은 오류가 발생하였습니다.
![image](https://user-images.githubusercontent.com/42234701/98211330-3aa5fc00-1f85-11eb-953f-c30545105ca7.png)



이에 따라 에러를 분석하여 보니 인코딩 방식 때문인 것으로 보입니다.
https://docs.aws.amazon.com/ko_kr/cli/latest/userguide/cliv2-migration.html
문서를 살펴보니 **AWS CLI 버전 2에서 기본적으로 이진 파라미터를 base64 인코딩 문자열로 전달** 부분이 저희에게 문제가 된 것 같습니다. 문서를 보면 총 2가지가 있었습니다.
1. config file 세팅.
2. cli 인자에 추가하여 보냄.
두 가지 방식 모두 진행해 보았는데 두 가지 전부 잘 실행되는 것 확인했습니다

아래 사진과 같이
![image](https://user-images.githubusercontent.com/42234701/98211662-b6a04400-1f85-11eb-8ef6-3ce4181c227a.png)
cli에 **--cli-binary-format raw-in-base64-out**를 추가하거나 
문서에 나와있는 ~/.aws/config 파일에 cli_binary_format=raw-in-base64-out 를 추가하거나 였습니다. 

    cmd += ['--cli-binary-format', 'raw-in-base64-out']

2020-11-05 07:54 UTC, rkdgusrnrlrl requested changes
명규님이 aws cli2 에는 기본적을 base64 인코딩이 강제 되어 있는 것 같네요. 이 부분만 수정 하면 문제 없을듯 합니다.

2020-11-06 02:43 UTC, yoonjs2 commented
> import-key-pair

@GoldieKMG // 시간상 전체 create/terminate 검증은 못해봤는데요 대신 검사해주셔서 감사합니다 😊  base64 문제는 말씀하신대로 문서를 보고 인지하고 있긴했는데 우리 소스에서 관련된 내용이 있을줄은 몰랐네요.
 https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html

2020-11-06 05:33 UTC, yoonjs2 commented
@rkdgusrnrlrl @GoldieKMG // 수정 완료하여 merge 하겠습니다.

2020-11-06 05:34 UTC, merged