DEV-9876 run_create_s3_script_lifecycle.py 파일 run_create_s3에 통합
HardBoiledSmith/johanna pull request #427
Opened 2021-01-11 08:00 UTC by GoldieKMG

### What is this PR for?
- run_create_s3_script_file_lifecycle.py 를 별도로 돌려야 해서 *-hbsmith-script-new 버킷에 lifecycle 적용이 빠져 있는 경우가 있음 → 삭제마킹 되었으나 실제로는 지워지지 않은 버전이 누적됨
- run_create_s3_script_file_lifecycle.py 을 run_create_s3_bucket.py에 통합. 
- bucket에 versioning 켜져 있으면 script_file_manage_rule 을, 아니면 result_file_manage_rule 을 적용
- default-config.json 에서 script 버킷에도 EXPIRE_FILES_DAYS 를 7일로 유지

### How should this be tested?
- johanna를 띄운 후 `./run_create_s3.py <your script bucket>` 을 실행시켜 주세요.
- S3 스크립트 버킷에 life cycle이 잘 적용 되었는지 확인해 주세요.

### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/42234701/104156694-ffb0c080-542c-11eb-950e-94dff46e9569.png)

2021-01-11 08:10 UTC, GoldieKMG commented on run_create_s3_bucket.py
> +    if 'hbsmith-script' in bucket_name:
https://github.com/HardBoiledSmith/johanna/pull/427/files#diff-3c384b051caf37ee96d8d0c83c6714542e44caa523a1fac78205ecd6a46ea29dR105 라인에 통합시켜 작성해 보니 파악해보는데 좀 더 복잡하겠다는 생각이 들어 별도로 분리하였습니다.

2021-01-12 03:20 UTC, yoonjs2 requested changes

2021-01-12 03:20 UTC, yoonjs2 commented on run_create_s3_bucket.py
> +    if 'hbsmith-script' in bucket_name:
@GoldieKMG // 로직이 통합되면 좀더 범용성이 있어 보이겠지만 현재 상황으로서는 이정도 로직으로 적당한것 같습니다. 한가지 개선 의견이 있다면 expire_days 같은 경우 versioning = enable 인 때와 그렇지 않은 때 모두 같이 사용하고 있어서 103L에서 return 처리를 실수로 빼버리면 105L 아래 로직이 진행되어 원치않는 object 삭제가 되어버린느 결과가 생길것 같긴 하네요. 이런경우 versioning 도 꺼져 있기 때문에 복구도 못할 문제가 있습니다.

2021-01-12 03:20 UTC, yoonjs2 commented on run_create_s3_bucket.py
> +                            "NoncurrentDays": expire_days
@GoldieKMG // 위에서 의견 드렸지만 만일의 경우를 대비하기 위해 아예 다른 변수를 명시적으로 선언해서 쓰는걸 제안드립니다.
```suggestion
                            "NoncurrentDays": versioning_expire_days
```

2021-01-12 03:24 UTC, singetta approved these changes
@GoldieKMG // create_s3_script_lifecycle, terminate_s3_script_lifecycle이 하나의 스크립트에서 실행되도록 잘 구현 하신 것 같습니다.

2021-01-12 06:21 UTC, yoonjs2 requested changes
@GoldieKMG // 그리고 제거하신 run_terminate_s3_script_lifecycle.py 의 기능도 run_terminate_s3_bucket에 들어가야 할것 같은데 확인 부탁드립니다.

2021-01-12 07:25 UTC, GoldieKMG commented on run_create_s3_bucket.py
> +    if 'hbsmith-script' in bucket_name:
@yoonjs2 // 그 부분이 고민이 많이 되어 최대한 고려하여 작성하였었는데 주신 의견이 현 코드 상 가장 명확하고 좋을 것 같습니다 
항시 그런건 아니지만 기존 코드에 기능을 추가(환경변수도 추가) 하면서 문제가 없게 하기 위해선 따로 분리하는게 좋은 것 같습니다 배움주셔 고맙습니다 🙏

2021-01-12 07:36 UTC, GoldieKMG commented
> @GoldieKMG // 그리고 제거하신 run_terminate_s3_script_lifecycle.py 의 기능도 run_terminate_s3_bucket에 들어가야 할것 같은데 확인 부탁드립니다.

@yoonjs2 // https://github.com/HardBoiledSmith/johanna/blob/70810b0badf266c94ca484496e0fa6f8c96bdd66/run_terminate_s3_script_lifecycle.py#L32 코드는 
https://github.com/HardBoiledSmith/johanna/blob/70810b0badf266c94ca484496e0fa6f8c96bdd66/run_terminate_s3_bucket.py#L19 에 포함이 되어 있어 별도로 작성하진 않았습니다
코드 작성 당시 lifecycle만을 위했었는데 통합하면서 중복되는 내용이라 파일을 지웠습니다

2021-01-14 06:52 UTC, yoonjs2 approved these changes

2021-01-15 04:21 UTC, merged