DEV-11312 cloudwatch alarm에 sachiel, nerv에서 발생하는 예외로그에 대한 알람 추가
HardBoiledSmith/johanna pull request #460
Opened 2021-04-05 12:36 UTC by GoldieKMG

### What is this PR for?
httpd, nginx exception 등은 알람 메일로 수집이 안되기 때문에 cloudwatch log에 알람 설정 추가 필요 

참고 사이트 : https://theithollow.com/2017/12/11/use-amazon-cloudwatch-logs-metric-filters-send-alerts/

- sachiel, nerv 서버에 대한 처리 필요
    - /aws/elasticbeanstalk/nerv-*/var/log/nginx/error.log
    - /aws/elasticbeanstalk/sachiel-*/var/log/httpd/error_log

관련 PR
magi

### How should this be tested?
- johhanna에서 ./run.py create_iam, vpc, rds를 띄어주세요.
- /run_create_ec2_client_vpn.py를 실행 후 ovpn을 발급받아주세요.
- 발급완료 후 rds에 데이터를 넣어주세요.
- ./run.py create_sqs , create_sns를 실행해 주세요.
- ./run_create_eb.py sachiel
- ./run_create_eb.py nerv를 실행해 주세요.
- ./run_create_lambda.py cloudwatch_send_alarm 을 실행 해 주세요.

app console에 접속하여 cloudwatch 서비스로 접속 해주세요.
- /aws/elasticbeanstalk/nerv-*/var/log/nginx/error.log
- /aws/elasticbeanstalk/sachiel-*/var/log/httpd/error_log
위 두 로그 그룹에 대해서 filter와 cloudwatch alarm이 SNS(cloudwatch-alarm)으로 걸려있는지 확인해주세요. 

eb create에 넣은 이유는 eb가 생성된 이 후 filter를 설정해야 하고, cloudwatch alarm을 걸어주어야 하여 create에 지정하였습니다.
terminate_eb와 old_eb 두 군대에 넣은 이유는 cloudwatch에 걸어둔 filter의 경우 eb가 정리되며 삭제가 되지만, cloudwatch alarm의 경우 자동으로 삭제 되지 않아 cron으로 old_eb_termiante 할 때와 eb_terminate 두 군대 넣어두었습니다.

### Screenshots (if appropriate)
cloudwatch 알람이 적용 된 이후 sns 토픽으로 지정된 lambda로 발송
nerv = nginx_error_log, sachiel = httpd_error_log
![image](https://user-images.githubusercontent.com/42234701/113574323-cddb7e80-9656-11eb-9460-2d55f457febc.png)

old_eb 종료
![image](https://user-images.githubusercontent.com/42234701/113574071-560d5400-9656-11eb-8b54-9eafb15052b3.png)
App console EB
![image](https://user-images.githubusercontent.com/42234701/113574242-a84e7500-9656-11eb-9315-c73953117103.png)

old 종료 후 남은 cloudwatch alarm ( 떠있는 신형 instance만 alarm 존재함 확인)
![image](https://user-images.githubusercontent.com/42234701/113574128-73422280-9656-11eb-91a8-044faa863fac.png)

eb_terminate 실행 시 (모든 eb관련 cloudwatch alarm은 제거)
![image](https://user-images.githubusercontent.com/42234701/113574182-8f45c400-9656-11eb-820e-500f8e86c7a1.png)

2021-04-05 12:59 UTC, GoldieKMG commented on run_create_eb_django_al2.py
> +            cmd += ['--filter-pattern', '']
patten의 경우 여러 가지를 조건에 대해서도 처리가 가능했습니다. 단, 현재 저희 로그가 어떤 부분을 안봐도 되는지, 봐야되는지 등에 대해 쌓인 부분이 없어 모든 부분에 대해서 잡히도록 설정하였습니다.

https://docs.aws.amazon.com/ko_kr/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html

2021-04-05 12:59 UTC, GoldieKMG commented on run_create_eb_django.py
> +            cmd += ['--filter-pattern', '']
patten의 경우 여러 가지를 조건에 대해서도 처리가 가능했습니다. 단, 현재 저희 로그가 어떤 부분을 안봐도 되는지, 봐야되는지 등에 대해 쌓인 부분이 없어 모든 부분에 대해서 잡히도록 설정하였습니다.

https://docs.aws.amazon.com/ko_kr/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html

2021-04-06 04:42 UTC, yoonjs2 requested changes
@GoldieKMG // 적절하게 구현을 잘 해주셨는데요, 약간만 더 보완하고 싶습니다 :)

2021-04-06 04:42 UTC, yoonjs2 commented on run_create_eb_django.py
> +    if name == 'sachiel':
@GoldieKMG // 모든 django 서버에 대해서 이 기능(에러 로깅 알림)을 강제할 생각이라 분기처리는 빼셔도 될것 같습니다.
```suggestion
```

2021-04-06 04:42 UTC, yoonjs2 commented on run_create_eb_django.py
> +            cmd += ['--filter-pattern', '']
@GoldieKMG // 적용 감사합니다. 한가지 약간 우려되는 점은 error_log 파일에 에러가 아니라 그냥 stderr 에서 찍히는 메세지도 같이 보이기 때문에 너무 빨리 알람이 걸리면 아래와 같은 에러가 아닌 메세지 때문에 false 알림이 발생할수도 있을것 같습니다. 혹시 개발하는 동안 문제는 없었나요?
<img width="2244" alt="Screen Shot 2021-04-06 at 1 21 12 PM" src="https://user-images.githubusercontent.com/1650254/113659618-5e5ca200-96dd-11eb-9f66-c9436159d06f.png">

2021-04-06 04:42 UTC, yoonjs2 commented on run_create_eb_django_al2.py
> +            cmd += ['--filter-pattern', '']
@GoldieKMG // 적용 감사합니다. 한가지 약간 우려되는 점은 error_log 파일에 에러가 아니라 그냥 stderr 에서 찍히는 메세지도 같이 보이기 때문에 너무 빨리 알람이 걸리면 아래와 같은 에러가 아닌 초기화 메세지 때문에 false 알람이 발생할수도 있을것 같습니다. 혹시 개발하는 동안 문제는 없었나요?
<img width="2244" alt="Screen Shot 2021-04-06 at 1 21 12 PM" src="https://user-images.githubusercontent.com/1650254/113659683-8b10b980-96dd-11eb-94d8-438b4402db54.png">

2021-04-06 04:42 UTC, yoonjs2 commented on run_create_eb_django_al2.py
> +    if name == 'nerv':
@GoldieKMG // 모든 django 서버에 대해서 이 기능(에러 로깅 알림)을 강제할 생각이라 분기처리는 빼셔도 될것 같습니다.
```suggestion
```

2021-04-06 04:42 UTC, yoonjs2 commented on run_terminate_eb.py
> +                if 'nerv' in r['EnvironmentName']:
@GoldieKMG // 모든 django 서버에 대해서 이 기능(에러 로깅 알림)을 강제할 생각이라 분기처리는 빼셔도 될것 같습니다.
```suggestion
```

2021-04-06 04:42 UTC, yoonjs2 commented on run_terminate_eb.py
> +                if 'sachiel' in r['EnvironmentName']:
@GoldieKMG // 모든 django 서버에 대해서 이 기능(에러 로깅 알림)을 강제할 생각이라 분기처리는 빼셔도 될것 같습니다.
```suggestion
```

2021-04-06 04:42 UTC, yoonjs2 commented on run_terminate_eb_old_environment.py
> +        if 'nerv' in r['EnvironmentName']:
@GoldieKMG // 모든 django 서버에 대해서 이 기능(에러 로깅 알림)을 강제할 생각이라 분기처리는 빼셔도 될것 같습니다.
```suggestion
```

2021-04-06 04:42 UTC, yoonjs2 commented on run_terminate_eb_old_environment.py
> +        if 'sachiel' in r['EnvironmentName']:
@GoldieKMG // 모든 django 서버에 대해서 이 기능(에러 로깅 알림)을 강제할 생각이라 분기처리는 빼셔도 될것 같습니다.
```suggestion
```

2021-04-07 02:09 UTC, GoldieKMG commented on run_create_eb_django.py
> +    if name == 'sachiel':
@yoonjs2 // 
요구사항에서 아래와 같이 처리를 하였습니다. 리뷰 내용에서는 django는 nginx, httpd 둘 다 걸어준다는 뜻으로 이해하면 될까요? 작업 초기 당시 각 저장소에 따라 특정 로그만 의도적으로 걸어두려 하신 것으로 파악했습니다. 제가 아직 에러 로그에 대한 지식 폭이 좁아 모든 부분을 생각해보지 못하는 것 같습니다

- nerv
/aws/elasticbeanstalk/nerv-*/var/log/nginx/error.log
- sachiel
/aws/elasticbeanstalk/sachiel-*/var/log/httpd/error_log

현재는 sachiel은 al1 (run_create_eb_django.py) , nerv는 al2 (run_create_eb_django_al2.py)를 사용하고 있어 크게 문제가 없을 것으로 보이나, 추 후 sachiel도 al2로 갈 경우 https://github.com/HardBoiledSmith/johanna/pull/460/files#diff-7cdb75ab33b45e1ef4d4db607d9aa5b1bc71430d890d2f09abca82e9c171ece4R471
이 부분에 실수를 방지하기 위해 
![image](https://user-images.githubusercontent.com/42234701/113800054-375fa800-9791-11eb-8d64-704ceed86e84.png)
metricNamespace 변수 명을 변경하는게 좋을 것 같습니다
ex) httpd, nginx를 프리픽스로 붙여주는게 좋을 듯 합니다

2021-04-07 02:27 UTC, yoonjs2 commented on run_create_eb_django.py
> +    if name == 'sachiel':
@GoldieKMG // https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.cloudwatchlogs.html 문서 보시면 AL2 플랫폼의 경우 nginx와 httpd 양쪽을 다 쓰는 것처럼 보이지만 (실제론 httpd와 nginx 둘중 하나를 선택할수 있습니다.) 우리는 nginx만 쓰기 때문에 ngnix에만 로그가 모이게 됩니다. 따라서 굳이 HTTPD_METRIC_NAME_SPACE, NGINX_METRIC_NAME_SPACE 이렇게 구분할 필요가 없습니다. 그리고 생각해보니 METRIC_NAME_SPACE를 굳이 magi로 빼야 하는지도 의문입니다. 아래와 같이 수정을 제안 드립니다.

1) magi에서 METRIC_NAME_SPACE 항목 제거
2) johanna에서 sachielProxyErrorLog, nervProxyErrorLog 으로 이름을 만들어서 할당

2021-04-07 04:56 UTC, GoldieKMG commented on run_create_eb_django.py
> +    if name == 'sachiel':
@yoonjs2 // 넵 말씀해주셔서 이해했습니다 추가 설명 주셔서 고맙습니다
![image](https://user-images.githubusercontent.com/42234701/113810999-587ec380-97a6-11eb-8d54-d57d802c1004.png)
python 플랫폼의 경우 error_log, error.log가 기록 된다는 점 확인 했습니다. 현재 저희는 al1의 경우 Httpd를 쓰고있고, al2의 경우는 nginx에 로그를 기록을 하고 있으니 파일에 따로 합칠 필요는 없겠네요. sachiel, nerv에 따라서 되도록 처리 하겠습니다

2021-04-07 07:24 UTC, GoldieKMG commented on run_create_eb_django.py
> +            cmd += ['--filter-pattern', '']
@yoonjs2 // 
nerv, sachiel 둘 다 문제 없었습니다. nerv의 경우는 새로운 환경이 떠도 특별한 로그가 뜨지 않아 문제 될 부분이 없었습니다. sachiel의 경우는 위 제상님께서 올린 스크린샷과 동일하게 strerr등 에러등이 있었는데요, sns -> lambda(slack)를 통해 도착한 메세지는 환경을 띄울 때 발생하는건은 없었습니다.

2021-04-09 03:16 UTC, yoonjs2 approved these changes

2021-04-09 03:16 UTC, merged