DEV-11378 Cloudwatch Dashboard Search Expression 지원
HardBoiledSmith/johanna pull request #461
Opened 2021-04-07 05:09 UTC by byunjuneseok

### What is this PR for?
- Cloudwatch Dashboard Search Expression 지원

### How should this be tested?
- `config.json` 에 dashboard 를 추가합니다. ("TYPE" 에 "search_expression" 지정)
```json
{
  "cloudwatch": {
    "DASHBOARDS": [
      {
        "AWS_DEFAULT_REGION": "ap-northeast-2",
        "NAME": "sachiel_new",
        "TYPE": "search_expression"
      },
    ]
  }
}
```
- magi 에서 `sachiel_new_ap-northeast-2.json` 을 작성합니다.
```json
{
  "widgets": [
    {
      "height": 6,
      "properties": {
        "metrics": [
          [ { "expression": "SEARCH('{AWS/ElasticBeanstalk,EnvironmentName} MetricName=\"ApplicationRequests2xx\" sachiel-', 'Sum', 60)", "id": "e1", "period": 60, "visible": false } ],
          [ { "expression": "MAX(e1)", "id": "e2", "period": 60 } ]
        ],
        "view": "timeSeries",
        "stacked": false,
        "region": "ap-northeast-2",
        "stat": "Sum",
        "title": "ApplicationRequests2xx"
      },
      "type": "metric",
      "width": 6,
      "x": 0,
      "y": 0
    }
  ]
}

```
- 관련 인프라를 프로비저닝합니다. (iam, vpc, rds, sachiel, sachiel)
- 명령어가 잘 실행되어야 합니다.
```
$ ./run_create_cloudwatch_dashboard.py sachiel_new
```
- 아래 스크린샷 처럼 확인되어야 합니다.
<img width="3120" alt="스크린샷 2021-04-07 오후 2 08 03" src="https://user-images.githubusercontent.com/29401441/113813334-ae556a80-97aa-11eb-84cf-589c0ec1ea8a.png">
<img width="3120" alt="스크린샷 2021-04-07 오후 2 08 22" src="https://user-images.githubusercontent.com/29401441/113813354-b90fff80-97aa-11eb-9070-4236374b7a8a.png">

- 대시보드가 잘 삭제되어야 합니다.
```
$ ./run_terminate_cloudwatch_dashboard.py sachiel_new
```

2021-04-08 07:17 UTC, GoldieKMG commented
@byunjuneseok // 저도 잠깐 찾아봤는데 명확하게 방법이 나오진 않네요.. 
sachiel, nerv를 명확하게 나누기는 좀 어려운 면이 잇네요 그래프는 우선 다 보이게는 가능한 것 같습니다.
![image](https://user-images.githubusercontent.com/42234701/113967656-626afa00-986c-11eb-8ef4-b73dd7c042a0.png)

SEARCH('{AWS/ApplicationELB,LoadBalancer,TargetGroup} MetricName=\"HealthyHostCount\" NOT MetricName=\"UnHealthyHostCount\"', 'Average', 300)

위의 코드 추가로도 보는건 가능하지만 명확히 하지 않는 다는 점이 존재하는게 있네요..
어떤식으로 정확히 gendo, sachiel, nerv를 띄워놓을 수 있을지는 고민을 좀 더 해봐야 알 것 같습니다

별도로 커스텀 지표를 생성하면 되긴하겠지만 현재 기준에서 적은 수정으로 할 수 있는 방향이 떠오르면 공유 드리겠습니다

2021-04-09 02:02 UTC, yoonjs2 requested changes
@byunjuneseok // 다음의 방식으로 높은 우선순위로 진행해 주시면 감사하겠습니다.
- sachiel, gendo, nerv 3종 모두 교체
- 별도의 new 대시보드 만들지 않고 기존 EB 대시보드를 새 내용으로 대체한다. (집계에 이상이 있을경우 W16/17내 수정)
- 1개월 이상 값이 없는 위젯은 삭제한다
- EB environment 이름으로 묶는것만 묶고 나머지는 기존걸 그대로 쓴다.
- webex sqs 쪽 metric 추가는 W16/17로 미룬다.

2021-04-09 02:02 UTC, yoonjs2 commented on run_create_cloudwatch_dashboard.py
> +    elif cw_dashboard_env['TYPE'] == 'elasticbeanstalk':
@byunjuneseok // run_create_cw_dashboard_search_expression() 을 따로 만들지 말고 run_create_cw_dashboard_elasticbeanstalk()에 불필요한 로직을 걷어내고 run_create_cw_dashboard_search_expression() 의 내용을 통합하는게 어떨까요?

2021-04-14 01:41 UTC, yoonjs2 commented
@byunjuneseok // https://github.com/HardBoiledSmith/magi/pull/750 최신 수정본을 보니 기존 대시보드와 math expression을 통합 하셨기 때문에 magi에 아래와 같은 설정 추가가 필요한지 궁금합니다. 마지막으로 데일리 스크럼때 논의한건 구형 대시보드에 math expression을 통합 하면서 새로운 `TYPE: search_expression`을 추가하지 않고 johanna 의 레거시도 math expression과 구형 로직을 섞어 쓰도록 수정하는 것이었는데 혹시 제가 잘못알고 있는것일까요?
```
{
  "cloudwatch": {
    "DASHBOARDS": [
      {
        "AWS_DEFAULT_REGION": "ap-northeast-2",
        "NAME": "sachiel_new",
        "TYPE": "search_expression"
      },
    ]
  }
}
```

2021-04-14 02:49 UTC, byunjuneseok commented
@yoonjs2 // 네, 맞습니다. 제거하겠습니다.

2021-04-14 02:59 UTC, byunjuneseok commented
@yoonjs2 // 제상님께서 코멘트를 보고 혹시 제가 config 에 관련 설정을 남기고 PR요청드린 줄 알고 제거하겠다고 말씀드렸습니다.

> HardBoiledSmith/magi#750 최신 수정본을 보니 기존 대시보드와 math expression을 통합 하셨기 때문에 magi에 아래와 같은 설정 추가가 필요한지 궁금합니다.

말씀하신 대로 통합하였기 때문에 설정이 필요 없습니다.


> 마지막으로 데일리 스크럼때 논의한건 구형 대시보드에 math expression을 통합 하면서 새로운 TYPE: search_expression을 추가하지 않고 johanna 의 레거시도 math expression과 구형 로직을 섞어 쓰도록 수정하는 것이었는데 혹시 제가 잘못알고 있는것일까요?

이것도 맞고 말씀하신것처럼 johanna를 수정하였습니다. 


말씀하신 그대로 수정 완료되었습니다. 코드 최적화 부분이 남아있는데 이는[후속 이슈](https://hbsmith.atlassian.net/browse/DEV-10892) 에 더 볼 예정입니다.

감사합니다.

2021-04-14 03:19 UTC, yoonjs2 commented
> @yoonjs2 // 제상님께서 코멘트를 보고 혹시 제가 config 에 관련 설정을 남기고 PR요청드린 줄 알고 제거하겠다고 말씀드렸습니다.
> 
> > [HardBoiledSmith/magi#750](https://github.com/HardBoiledSmith/magi/pull/750) 최신 수정본을 보니 기존 대시보드와 math expression을 통합 하셨기 때문에 magi에 아래와 같은 설정 추가가 필요한지 궁금합니다.
> 
> 말씀하신 대로 통합하였기 때문에 설정이 필요 없습니다.
> 
> > 마지막으로 데일리 스크럼때 논의한건 구형 대시보드에 math expression을 통합 하면서 새로운 TYPE: search_expression을 추가하지 않고 johanna 의 레거시도 math expression과 구형 로직을 섞어 쓰도록 수정하는 것이었는데 혹시 제가 잘못알고 있는것일까요?
> 
> 이것도 맞고 말씀하신것처럼 johanna를 수정하였습니다.
> 
> 말씀하신 그대로 수정 완료되었습니다. 이번 PR에서 수정할 부분은 없는 것 같습니다. 코드 최적화 부분이 남아있는데 이는 [후속 이슈](https://hbsmith.atlassian.net/browse/DEV-10892) 에 더 볼 예정입니다.
> 
> 감사합니다.

@byunjuneseok // 감사합니다. 이 코멘트 읽고 준석님 코드를 다시 분석해보니 준석님 말이 맞네요. 준석님 의도를 제대로 못 읽은점 사과드립니다. ㅠ 첫번째 코멘트인 아래 코멘트만 보았을때엔 오해할 소지가 있었던것 같습니다. 앞으로 제가 어떠한 코멘트를 달아도 바로 반영하겠다고 리플달지 마시고 본인 의도를 짚어 주시면서 제가 부합되게 이해했는지 되물어 주시면 커뮤니케이션 하는데 도움이 될것 같습니다. 감사합니다 :) 

<img width="518" alt="Screen Shot 2021-04-14 at 12 12 56 PM" src="https://user-images.githubusercontent.com/1650254/114649352-558e5080-9d1b-11eb-9ae0-9b074a54e3e0.png">

2021-04-14 03:19 UTC, yoonjs2 approved these changes

2021-04-14 03:21 UTC, byunjuneseok commented
@yoonjs2 // 리뷰 감사합니다! =]

2021-04-14 03:21 UTC, merged