DEV-11661 **wip** kaji Code 내에서 aws credentials 제거
HardBoiledSmith/johanna pull request #471
Opened 2021-04-21 14:42 UTC by byunjuneseok

### What is this PR for?
- WIP

### How should this be tested?
- WIP

### Screenshots (if appropriate)
- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)

2021-04-23 04:52 UTC, yoonjs2 requested changes

2021-04-23 04:52 UTC, yoonjs2 commented on run_create_lambda_ses_sqs.py
> +
@byunjuneseok // 테스트에 쓰신 코드가 삭제가 안된것 같습니다. 확인 부탁드려요.

2021-04-24 04:29 UTC, byunjuneseok commented on run_create_lambda_ses_sqs.py
> +
@yoonjs2 // 삭제하였습니다.

2021-04-26 02:46 UTC, yoonjs2 approved these changes
@byunjuneseok // 감사합니다. IAM Policy가 변경되었기 때문에 OP에선 수동으로 변경해줘야 합니다. 이부분 패치할때 미리 공유해 주시면 감사하겠습니다.

2021-04-26 02:49 UTC, merged