DEV-11854 AWS Lambda 배포 기능 고도화 - IAM Role / Policy 를 각 lambda별로 생성
HardBoiledSmith/johanna pull request #486
Opened 2021-05-19 04:47 UTC by byunjuneseok

### What is this PR for?
#### kaji의 변경점
- `lambda/*/iam/role.json` 으로 iam role을 정의합니다.
- `lambda/*/iam/policy.json` 으로 iam policy를 정의합니다.

#### johanna의 변경점
- `./run_create_lambda.py` 실행 시 
    1. `lambdas_list` 를 순회하면서 IAM role 를 생성합니다. (이유 : 120초 전파 기간이 있기 때문에, 한 번에 모든 람다의 IAM role을 만들고 전파 기간을 기다리는게 시간 효율적)
    2. `role_created = True` 라면 120초 대기
    3. lambda 생성 로직 수행

- `./run_create_lambda.py <LAMBDA_NAME>` 실행 시
    1. `run_create_lambda_<TYPE>()` 안에서 IAM role 이 생성됩니다.
    2. lambda 생성 로직 수행

- `./run_terminate_lambda.py` 실행 시 or `run_terminate_lambda.py <LAMBDA_NAME>` 실행 시
    1. lambda 종료 로직 수행
    2. IAM 삭제 로직 수행

### How should this be tested?
1. vagrant 의 johanna 를 DEV-11854 로 맞춥니다.
2. vagrant johanna 박스의 `/opt/johanna/template/kaji` 를 DEV-11854 로 맞춥니다.
3. `./run_create_lambda.py` 를 수행합니다.
4. 모든 iam role 이 iam policy 와 함께 만들어졌는지 AWS 콘솔에서 확인합니다.
5. lambda 가 잘 생성되고 기능하는지 확인합니다.
6. `./run_terminate_lambda.py` 를 수행하여 lambda 와 IAM role 이 모두 삭제되었는지 확인합니다.
7. `./run_create_lambda.py <LAMBDA_NAME>` 같은 명령어로 4~6을 확인합니다.

2021-05-20 01:44 UTC, singetta commented on run_create_lambda.py
> +            role_created = rr
@byunjuneseok // ./run_create_lambda.py -f 실행 시 template에 kaji 가 다운로드 받지 않은 상태에서는 create_iam_for_lambda에서 에러가 발생합니다.

2021-05-20 01:48 UTC, singetta requested changes
@byunjuneseok // lambda별 create, terminate 확인하였습니다. 하지만 ./run_create_lamda.py 만 실행할 경우 초기 template파일에 kaji 다운로드 유무를 판단하는 코드가 필요해보입니다.

2021-05-20 01:48 UTC, singetta commented on run_create_lambda.py
> +        rr = create_iam_for_lambda(git_folder_name, folder_name, lambda_env['NAME'])
@byunjuneseok // ./run_create_lambda.py -f 실행 시 template에 kaji 가 다운로드 받지 않은 상태에서는 create_iam_for_lambda에서 에러가 발생합니다. template 내 kaji 다운로드 유무 확인 및 없다면 git clone하여 다운로드 받는 로직이 추가되야 할 듯 합니다.

2021-05-20 04:03 UTC, yoonjs2 requested changes

2021-05-20 04:03 UTC, yoonjs2 commented on run_create_lambda.py
> +
@byunjuneseok // 이렇게 role을 한꺼번에 만드는 것보다 필요할때 존재유무를 확인해서 만들도록 하는게 어떨까 합니다. 그래야 문제가 생길때 원인 분석 및 범위 좁히는데 도움이 됩니다. 그리고 그동안 개선이 좀 되었는지 10초 정도만 기다려도 role 가져오는데 큰 문제가 없었습니다. 아래 Codebuild 쪽 구현을 참고하셔서 codebuild와 유사하게 role, policy 세팅을 하도록 구현을 변경해 주실것을 요청드립니다. 구현이 비슷해야 다른 개발자들도 빨리 파악해서 수정이 가능합니다.

https://github.com/HardBoiledSmith/johanna/blob/308f1b4233997c1935f4ad7cb77a0d7a98085fa5/run_create_codebuild_cron.py#L40-L48

2021-05-20 04:03 UTC, yoonjs2 commented on run_create_lambda.py
> +        rr = create_iam_for_lambda(git_folder_name, folder_name, lambda_env['NAME'])
@byunjuneseok // 민수님 의견을 참고해서 수정 부탁드립니다.

2021-05-21 09:21 UTC, yoonjs2 approved these changes

2021-05-21 09:29 UTC, byunjuneseok commented
@singetta // 리뷰 감사드립니다! @yoonjs2 님의 의견에 따라 한 번에 모든 lambda를 생성할 때 iam role 을 생성하는 로직이 삭제되었으므로, 말씀 주신 체크 로직은 필요가 없어진 것 같습니다.

2021-05-21 09:30 UTC, merged