DEV-11977 (in-progress) lambda 관련 알람을 alarm 에서 제거하고 __global__ 에 모든 람다들의 Error 율을 추적하는 알람 추가
HardBoiledSmith/johanna pull request #488
Opened 2021-05-27 07:15 UTC by yoonjs2

### What is this PR for?
- 이 PR이 해결하고자 하는 이슈(JIRA Issue) 및 작업 내용에 대해 설명해 주세요

### How should this be tested?
- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요

### Screenshots (if appropriate)
- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)

2021-06-09 13:12 UTC, GoldieKMG approved these changes
고생하셨습니다 🙏

2021-06-11 02:12 UTC, singetta requested changes
@yoonjs2 // 아래 코드 확인 부탁드립니다.

2021-06-11 02:12 UTC, singetta commented on run_create_cloudwatch_alarm.py
> +    dd['MetricStat']['Metric']['Dimensions'] = []
```suggestion
    dd['MetricStat']['Metric']['Dimensions'] = list()
```
list() 선언으로 변경하는게 어떨까요?

2021-06-13 09:56 UTC, yoonjs2 commented on run_create_cloudwatch_alarm.py
> +    dd['MetricStat']['Metric']['Dimensions'] = []
@singetta // 제안 감사합니다. 저도 놓치고 있었네요 ;)

2021-06-14 01:02 UTC, singetta approved these changes

2021-06-14 08:47 UTC, merged