DEV-11972 sentry-cli를 사용할때 sourcemap도 같이 업로드 되도록 수정
HardBoiledSmith/johanna pull request #502
Opened 2021-06-20 03:16 UTC by byunjuneseok

### What is this PR for?
- sourcemap 업로드 기능 추가
- (이슈 외) vagrant johanna 에서 sentry 사용 기능 시, error 발생 문제 수정

### How should this be tested?
- sentry 에서 새로운 테스트용 organization 생성 및 hbsmith-web-app 을 생성합니다.
- 새로운 DSN 로 johanna 의 config.json 의 sentry dsn 값을 교체합니다.
- `./run_create_s3.py app`
- 아래의 스크린샷처럼 업로드가 잘 되어야 합니다.
<img width="1616" alt="스크린샷 2021-06-20 오후 12 14 27" src="https://user-images.githubusercontent.com/29401441/122661013-123fda80-d1c1-11eb-8c3a-7ceb777e5349.png">

- sentry project settings 안에 Source maps 탭에서도 확인할 수 있어야 합니다.
<img width="1616" alt="스크린샷 2021-06-20 오후 12 15 28" src="https://user-images.githubusercontent.com/29401441/122661034-38657a80-d1c1-11eb-8401-a0e85e2841c1.png">

2021-06-30 09:23 UTC, yoonjs2 requested changes
@byunjuneseok // vagrant에서 동작은 문제가 없는데 빠진게 있습니다.
- .sentryclirc 세팅법에 대해 README.md 추가 부탁드립니다. 
- codebuild의 op_create_hbsmith_web 에서 돌리려면 .sentryclirc 에 대한 세팅을 아래에 추가해야 할것 같습니다. 확인바랍니다.
https://github.com/HardBoiledSmith/magi/blob/371c898cdf3ea3b9311099ad7e672e4173ba88ce/codebuild/op_create_hbsmith_web/buildspec.yml#L35

2021-07-02 02:03 UTC, GoldieKMG reviewed
기능구현 고맙습니다!
리뷰 반영되는대로 테스트 진행해보겠습니다 🙏

2021-07-02 09:16 UTC, singetta approved these changes
@byunjuneseok // 코드 및 동작 상으로 이슈는 없어 보입니다. 제상님 의견 확인 부탁드립니다. 🙏🏼

2021-07-05 08:13 UTC, byunjuneseok commented
@yoonjs2 // codebuild 에는 환경변수가 이미 포함되어있으므로 문제없이 진행될 것으로 파악됩니다. 

리뷰 감사합니다.

<img width="1091" alt="스크린샷 2021-07-05 오후 5 12 45" src="https://user-images.githubusercontent.com/29401441/124439310-3a7c2b80-ddb4-11eb-9a16-05c382ab7c0d.png">

2021-07-27 06:05 UTC, yoonjs2 approved these changes

2021-07-27 06:07 UTC, yoonjs2 commented
준석님 소스코드를 sentry 요구사항에 맞게 다시 수정하였습니다.

2021-07-27 06:07 UTC, merged