DEV-11304 vuejs web 배포후 OP 계정의 Cloudfront 캐시 강제로 invalidate 시키는 로직 추가
HardBoiledSmith/johanna pull request #504
Opened 2021-06-25 08:43 UTC by GoldieKMG

### What is this PR for?
**AS-IS**
- CloudFront가 OP계정에 있어 본인의 계정 cloudfront invalidate기능을 사용 하지 못함.

TO-BE
- OP 콘솔에 들어가 직접 invalidation 시키지 않아도 되도록 OP계정에 role을 생성하여 권한 위임.

### How should this be tested?
주의) OP키 값으로 IAM을 생성해야함으로 주의가 필요합니다. 계정 키 값을 변경하여 사용하는게 익숙하지 않다면 테스트를 하지 않는게 좋을 것 같습니다.

1) 해당 브랜치의 magi/_seele로 op와 dv config.json을 생성해주세요.
2) johhanna를 띄워주세요.
3) op키로 변경 후 ./run_create_cloudfront_iam_invaildations.py <Username to create role & policy>  <aws account id to allow> <cloudfront distribution id to allow>
ex) ./run_create_cloudfront_iam_invaildations.py danny 1234232222 ABCD23FYII 
4) 정책 및 역할이 생성 되었다면 ./run_create_s3.py app을 실행해 주세요.
app console이 뜬 후 invalidation 이 되는지 확인해 주세요. ( invalidation 코드 외 주석 후 테스트를 진행해도 됩니다.)

### Screenshots (if appropriate)
<img width="1672" alt="스크린샷 2021-06-25 오후 4 39 15" src="https://user-images.githubusercontent.com/42234701/123396995-e5cef880-d5dc-11eb-8555-57924ecf50f0.png">
<img width="805" alt="스크린샷 2021-06-25 오후 4 39 06" src="https://user-images.githubusercontent.com/42234701/123397005-e9627f80-d5dc-11eb-8463-5a75fc6e71d2.png">

2021-06-30 03:25 UTC, byunjuneseok approved these changes
@GoldieKMG // 작성 감사합니다.

comment 확인 부탁드립니다. 추가로 invalidations 복수명사로 파일명 작성하셨는데, 단수 명사로 수정하면 어떨까요?

2021-06-30 03:25 UTC, byunjuneseok commented on run_create_cloudfront_iam_invaildations.py
> +    lines = read_file('aws_iam/aws-cloudfront-Invalidations-role.json')
@GoldieKMG // `aws-cloudfront-invalidations-role.json`으로 대문자 I를 소문자 i로 수정이 필요할 것 같습니다.

2021-06-30 03:25 UTC, byunjuneseok commented on run_create_cloudfront_iam_invaildations.py
> +    lines = read_file('aws_iam/aws-cloudfront-Invalidations-policy.json')
@GoldieKMG // `aws-cloudfront-invalidations-policy.json`으로 대문자 I를 소문자 i로 수정이 필요할 것 같습니다.

2021-06-30 05:29 UTC, yoonjs2 requested changes

2021-06-30 05:29 UTC, yoonjs2 commented on run_create_cloudfront_iam_invaildations.py
> +    lines = read_file('aws_iam/aws-cloudfront-Invalidations-role.json')
@GoldieKMG // @byunjuneseok 님 의견에 동의합니다. 통일성을 위해 소문자로 맞춰 주세요.

2021-06-30 05:29 UTC, yoonjs2 commented on run_create_cloudfront_iam_invaildations.py
> +    lines = read_file('aws_iam/aws-cloudfront-Invalidations-policy.json')
@GoldieKMG // @byunjuneseok 님 의견에 동의합니다. 통일성을 위해 소문자로 맞춰 주세요.

2021-06-30 05:29 UTC, yoonjs2 commented on run_terminate_cloudfront_iam_invaildations.py
> +print_session('create iam user for use cloudfront invalidations')
@GoldieKMG // 텍스트가 잘못된것 같습니다. 확인 부탁드립니다.
```suggestion
print_session('terminate iam user for use cloudfront invalidations')
```

2021-06-30 05:29 UTC, yoonjs2 commented on run_create_s3_vue.py
> +            print(invalidate_result)
@GoldieKMG // STS에서 값을 가져온 후에 CLOUDFRONT_DIST_ID 를 확인후 invalidation을 수행하는데 보안을 위해 CLOUDFRONT_DIST_ID가 설정이 안되어 있으면 STS에서 값도 안가져 오도록 하면 어떨까 합니다. CLOUDFRONT_DIST_ID를 설정 안했다면 invalidation을 하지 않겠다는 의도로 예전에 구현했었거든요. 또한 STS에서 반드시 Credential을 가져와야 하니 `if rr:` 체크는 필요 없을것 같습니다.

```suggestion
        print_message('invalidate cache from cloudfront')

        cf_dist_id = settings.get('CLOUDFRONT_DIST_ID', '')
        if len(cf_dist_id) > 0:
        
           user_name = env['cloudfront']['USER_NAME']
           role_account_id = env['cloudfront']['IAM_OWNER_AWS_ACCOUNT_ID']
           cmd = ['sts', 'assume-role']
           cmd += ['--role-arn', f'arn:aws:iam::{role_account_id}:role/{user_name}-cloudfront-invalidations-role']
           cmd += ['--role-session-name', 'cloudfront-invalidation-token']
           rr = aws_cli.run(cmd)
           
           access_key = rr['Credentials']['AccessKeyId']
           secret_key = rr['Credentials']['SecretAccessKey']
           session_token = rr['Credentials']['SessionToken']
           aws_cli_for_cloudfront = AWSCli(aws_access_key=access_key,
                                                                    aws_secret_access_key=secret_key,
                                                                    aws_session_token=session_token)
        
            cmd = ['cloudfront', 'create-invalidation', '--distribution-id', cf_dist_id, '--paths', '/*']
            invalidate_result = aws_cli_for_cloudfront.run(cmd)
            print(invalidate_result)
```

2021-06-30 06:08 UTC, yoonjs2 requested changes
@GoldieKMG // 좀더 코드를 줄일 목적으로 아래 PR의 코멘트 제안에 맞춰 추가 수정 요청드립니다. https://github.com/HardBoiledSmith/magi/pull/785#pullrequestreview-695721749

2021-06-30 06:08 UTC, yoonjs2 commented on run_create_cloudfront_iam_invaildations.py
> +allow_role_aws_account_id = args[2]
```suggestion
```

2021-06-30 06:08 UTC, yoonjs2 commented on run_create_cloudfront_iam_invaildations.py
> +run_create_cloudfront_iam_for_invaildations(user_name, allow_role_aws_account_id, distribution_id)
```suggestion
run_create_cloudfront_iam_for_invaildations(user_name, distribution_id)
```

2021-06-30 06:08 UTC, yoonjs2 commented on run_create_cloudfront_iam_invaildations.py
> +def run_create_cloudfront_iam_for_invaildations(user_name, allow_role_aws_account_id, distribution_id):
```suggestion
def run_create_cloudfront_iam_for_invaildations(user_name, distribution_id):
```

2021-06-30 06:08 UTC, yoonjs2 commented on run_create_cloudfront_iam_invaildations.py
> +    iam_owner_aws_account_id = env['cloudfront']['IAM_OWNER_AWS_ACCOUNT_ID']
현재 스크립트를 돌리고 있는 대상 계정의 account id는 API로 가져올수 있습니다. 굳이 magi에서 입력받을 필요가 없습니다. https://github.com/HardBoiledSmith/johanna/blob/8521c64df8d172d4eb640cb95e41f619df465431/run_common.py#L230-L233
```suggestion
    iam_owner_aws_account_id = aws_cli.get_caller_account_id()
```

2021-06-30 06:08 UTC, yoonjs2 commented on run_terminate_cloudfront_iam_invaildations.py
> +    iam_owner_aws_account_id = env['cloudfront']['IAM_OWNER_AWS_ACCOUNT_ID']
@GoldieKMG //  현재 스크립트를 돌리고 있는 대상 계정의 account id는 API로 가져올수 있습니다. 굳이 magi애서 입력받을 필요가 없습니다. https://github.com/HardBoiledSmith/johanna/blob/8521c64df8d172d4eb640cb95e41f619df465431/run_common.py#L230-L233
```suggestion
    iam_owner_aws_account_id = aws_cli.get_caller_account_id()
```

2021-07-02 08:12 UTC, singetta requested changes
@GoldieKMG // 제상님 의견처럼 https://github.com/HardBoiledSmith/magi/pull/785 가 단순화되면 그만큼 수정해야할 코드들이 있어보입니다. 수정 후 다시 확인해보겠습니다.

2021-07-05 04:26 UTC, GoldieKMG commented on run_create_s3_vue.py
> +            print(invalidate_result)
넵! 반영하여 적용시켰습니다 :)

2021-07-05 04:26 UTC, GoldieKMG commented on run_create_s3_vue.py
> +    cmd += ['--role-arn', f'arn:aws:iam::{role_account_id}:role/{user_name}-cloudfront-invalidations-role']
넵 반영하였습니다 :)

2021-07-05 04:28 UTC, GoldieKMG commented on run_create_cloudfront_iam_invaildations.py
> +allow_role_aws_account_id = args[2]
@yoonjs2 // 
allow_role_aws_account_id 값은 정책 생성에 허용해줄 account_id값으로 필요한 값입니다  🙏 혹시 제가 변수명을 잘못 선택한 부분이 있을까요?

2021-07-06 04:59 UTC, yoonjs2 commented
@GoldieKMG // 명규님, OP계정에 role을 만들어서 seele 업데이트를 해야 본 기능이 사용 가능할것 같은데 OP 계정에 Role을 만들고 제게 알려주실래요? 그러면 seele에 제가 추가해 드리겠습니다.

2021-07-06 11:12 UTC, GoldieKMG reviewed
@yoonjs2 // 기존 로직에서 큰 변경없이 관리면에서 편리하도록 role 한 개에 app, test 페이지 권한 생성하도록 변경하였습니다.

2021-07-06 11:12 UTC, GoldieKMG commented on aws_iam/aws-cloudfront-invalidations-policy.json
> +                "arn:aws:cloudfront::ACCOUNT_ID:distribution/TEST_DISTRIBUTION_ID"
한개의 role에서 web, app에 대해 distribution_id 열어 주는게 관리면에서 좋을 것 같아 다음과같이 변경하였습니다.

2021-07-06 15:44 UTC, yoonjs2 approved these changes

2021-07-06 15:44 UTC, merged