DEV-12314 & DEV-12359 elastic beanstalk 프로비저닝 시 iam 개별 처리 및 policy update 를 위한 코드 수정
HardBoiledSmith/johanna pull request #505
Opened 2021-06-29 17:30 UTC by byunjuneseok

### What is this PR for?
- DEV-12314 
    - elastic beanstalk 프로비저닝 시 iam 을 환경 별로 분리하여 생성
- DEV-12359
    - lambda 재프로비저닝 시 iam 을 업데이트하도록 함
    - aws cli 에서 `put-role-policy` 는 업데이트도 수행하도록 되어있음 (https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/put-role-policy.html) 

### How should this be tested?
- `./run_create_vpc.py` 가 잘 수행되어야 합니다.
- `./run_create_eb.py` 가 잘 수행되어야 합니다.
- `./run_create_lambda.py` 가 잘 수행되어야 합니다.
- `./run_create_eb.py` 가 다시 잘 수행되어야 합니다. - iam 변경을 확인할 수 있어야 합니다, 이 때 git clone 은 DEV-12314 브랜치로 수행되어야 합니다.
- `./run_create_lambda.py` 가 다시 잘 수행되어야 합니다. - iam 변경을 확인할 수 있어야 합니다.
- app console 의 모든 기능이 잘 되어야 합니다.
- `./run_terminate_eb.py` 가 잘 수행되어야 합니다.
- `./run_terminate_lambda.py` 가 잘 수행되어야 합니다.
- `./run_terminate_vpc.py` 가 잘 수행되어야 합니다.

2021-06-30 04:50 UTC, yoonjs2 approved these changes
@byunjuneseok // 감사합니다. 정책 변경에 대해 빠트리지 않고 대응 가능하겠네요 :) 다만 이번 패치때 삭제한 run_terminate_iam.py 대신 수동으로 지우는 절차를 추가해야 할것 같습니다. (구형 EB가 모두 내려간 이후)

2021-06-30 09:11 UTC, yoonjs2 requested changes
@byunjuneseok // 코드를 다시 확인하니 미완성 또는 정리가 필요해 보이는 부분이 있네요 확인 부탁드립니다.

2021-06-30 09:11 UTC, yoonjs2 commented on run_create_eb_iam.py
> +    dotfile_path = f'template/{name}/{name}/_provisioning/.johanna'
@byunjuneseok //  이 코드를 참고한다면 sachiel, nerv, gendo 모두 _provisioning 폴더 아래 .johanna 폴더가 있어야 하는데 sachiel. nerv, gendo 저장소 모두 보이질 않네요;; 확인 부탁드립니다.

2021-06-30 09:11 UTC, yoonjs2 commented on run_create_eb_iam.py
> +    dotfile_path = f'template/{name}/{name}/_provisioning/.johanna'
그리고 sachiel, nerv, gendo 별로 따로따로 role, policy 파일을 둘거면 lambda의 그것과 유사하게 배치하는게 어떨까 합니다. 아래처럼 depth는 줄이고 파일명이 어떤 용도인지 드러나게 수정할 것을 제안합니다.
```
ec2 role: /sachiel/_provisioning/iam/aws-elasticbeanstalk-ec2-role.json
ec2 policy: /sachiel/_provisioning/iam/aws-elasticbeanstalk-ec2-policy.json
```
그리고 aws-elasticbeanstalk-service-role.json 도 environment 별로 분리하실건가요? 확인해보니 instance profile 와 달리 assume role 뿐이어서 sachiel, nerv, gendo 모두 권한이 다를게 없어 분리할 필요가 없어보이는데 의견 부탁드립니다.

2021-07-02 05:36 UTC, GoldieKMG reviewed
리뷰 반영되는대로 테스트 진행해보도록 하겠습니다 :)

2021-07-02 05:49 UTC, singetta reviewed
@byunjuneseok // 제상님 의견 확인 및 수정 후 다시 확인해보겠습니다.

2021-07-21 08:17 UTC, yoonjs2 commented
@HardBoiledSmith/code-reviewer 본 이슈는 완전한 재개발이 필요하여 close 하고 제가 새로 PR 올리도록 하겠습니다.

2021-07-21 08:17 UTC, closed without merging