DEV-1944 AWS 모니터링 툴 + Pager Duty 연동
HardBoiledSmith/johanna pull request #530
Opened 2021-09-16 07:11 UTC by GoldieKMG

### What is this PR for?
[AS-IS]
- AWS 자원 중 landing page, hbsmith web, sachiel, gedno에 대해 모니터링을 하기 위한 작업.

[TO-BE]
- 공개 망에 노출된 자원은 route53 health check 서비스를 통해 주기적으로 요청을 보내 이상이 생겼을 시 알림을 줌.
- Gendo같은 private자원은 별도의 cloud watch의 데이터 기준으로 이상을 체크.

알림의 순서는 cloudwatch -> sns -> pagerduty -> statuspage

### How should this be tested?
- 개인 세팅은 AWS 자원까지만 해당하며, Pageduty, Statuspage는 별도의 QA, DV를 위해 개설된 것은 없습니다.
- 해당 브랜치의 johanna, magi의 config 파일을 풀어주세요.
- magi에 각 개인별 -variable파일에 아래의 값을 추가해 주어야 합니다.
```
"PAGEDUTYAPPKEY_HBSMITH_WEB": "",
"PAGEDUTYAPPKEY_GENDO": "",
"PAGEDUTYAPPKEY_LANDING_PAGE": "",
"PAGEDUTYAPPKEY_SACHIEL": "",
"ROUTE53_HEALTH_CHECK_TARGET_DOMAIN_SACHIEL": "",
"ROUTE53_HEALTH_CHECK_TARGET_DOMAIN_HBSMITH_WEB": "",
"ROUTE53_HEALTH_CHECK_TARGET_DOMAIN_LANDING_PAGE": ""
 ``` 
- ROUTE53_HEALTH_CHECK_TARGET_DOMAIN... 의 값 3개는 테스트를 위해 OP환경에 서비스 되고있는 URL을 사용하면 됩니다.
```
  "ROUTE53_HEALTH_CHECK_TARGET_DOMAIN_SACHIEL": "op-sachiel.hbsmith.io",
  "ROUTE53_HEALTH_CHECK_TARGET_DOMAIN_HBSMITH_WEB": "app.hbsmith.io",
  "ROUTE53_HEALTH_CHECK_TARGET_DOMAIN_LANDING_PAGE": "www.hbsmith.io",
```
- ./run.py create_sns을 실행 후  ./run_create_route53_health_check.py 를 실행시켜주세요.
- AWS CONSOLE에 접속하여 SNS 및 Cloudwatch를 확인했을떄 아래의 사진과 같이 세팅이 되어있어야 합니다.
![image](https://user-images.githubusercontent.com/42234701/133566412-1505c07f-f47b-4168-8864-7108b1a5fd46.png)
![image](https://user-images.githubusercontent.com/42234701/133566498-c9057a8a-16a1-44c5-881a-dc7df75aeea1.png)

- Gendo의 경우는 기존의 topic명만 변경하였음으로 추가 테스트는 진행하지 않았습니다.

2021-09-16 07:25 UTC, GoldieKMG commented on run_create_sns.py
> +    if 'PAGERDUTYAPPKEY' in settings and settings['PAGERDUTYAPPKEY']:
Gendo Cloudwatch에 별도의 topic을 주기 위해 변경을 진행했습니다.
변경된 topic의 코드
https://github.com/HardBoiledSmith/magi/pull/816/files#diff-1294f9c4722a0792f3afe1bdc1c6d75b7339dff1fbd7264bf78867746126178fR246

2021-09-23 20:50 UTC, singetta approved these changes
@GoldieKMG // AWS CloudWatch에서 모니터링 내용 확인하였습니다. 기능 추가 감사합니다.

2021-09-27 15:57 UTC, yoonjs2 requested changes
@GoldieKMG // 고생하셨습니다. johanna 코드 컨벤션에 맞춰서 잘 수정헤 주셨네요 👍  다만 몇가지 의견이 있는데 확인해주시면 감사하겠습니다.

2021-09-27 15:57 UTC, yoonjs2 commented on run_create_sns.py
> +    if 'PAGERDUTYAPPKEY' in settings and settings['PAGERDUTYAPPKEY']:
@GoldieKMG // 이렇게 코드를 줄여볼수도 있을것 같습니다. :) 
```suggestion
    if settings.get('PAGERDUTYAPPKEY'):
```

2021-09-27 15:57 UTC, yoonjs2 commented on run_create_route53_health_check.py
> +                    "ap-northeast-1", "sa-east-1"]
@GoldieKMG // region에 ap-northeast-2는 없네요? 그리고 우리가 서비스를 서울리전에 접속하는 고객사 대상으로 하는거라 서울리전 외 다른리전을 굳이 추가해야하나 싶긴합니다. 이부분 확인 부탁드립니다.

2021-09-28 09:59 UTC, GoldieKMG commented on run_create_route53_health_check.py
> +                    "ap-northeast-1", "sa-east-1"]
health check를 수행하는 것들을 health checker라 지칭하겠습니다

health check 한 개를 생성할 때, health checker는 최소 3개  지정 해야합니다.( AWS 서비스규정 )
health check 수행 리전 추가에 따른 추가 요금 규정에 없습니다. 이용 기간에 따른 요금이 있습니다.
아쉽게도 health checker는 총 8개가 존재하고 서울은 따로 있지 않았습니다. 왜 없는지 등에 대한 사유는 못 찾았습니다

- health check region에 대한 설명 : https://docs.amazonaws.cn/en_us/Route53/latest/DeveloperGuide/health-checks-creating-values.html#health-checks-creating-values-health-checker-regions
- health check price
![image](https://user-images.githubusercontent.com/42234701/135065111-fc8ec195-3a34-4ed8-a3ab-f3a10cfe280a.png)
![image](https://user-images.githubusercontent.com/42234701/135065587-4761b465-7ee5-4fa2-8027-86a12d27bd3d.png)

2021-09-28 10:24 UTC, yoonjs2 commented on run_create_route53_health_check.py
> +                    "ap-northeast-1", "sa-east-1"]
@GoldieKMG // 그럼 아래 리전만 먼저 해볼까요? 잠재고객이 없는 지역에서 헬스체크하는건 낭비일것 같습니다.
- ap-northeast-1 (서울리전 대신 가장 가까운 지역)
- us-east-1 (가장 회선이 많고 오래된 리전)
- ap-south-1 (뭄바이 리전은 고객사 마카롱 때문에 추가했습니다.)

2021-09-28 10:32 UTC, GoldieKMG commented on run_create_route53_health_check.py
> +                    "ap-northeast-1", "sa-east-1"]
좋은 의견 주셔서 고맙습니다 :) 변경완료했습니다
![image](https://user-images.githubusercontent.com/42234701/135070907-32a2c729-598c-4f97-85c9-f8b9d9b07177.png)

2021-09-28 10:34 UTC, yoonjs2 commented on run_create_route53_health_check.py
> +                    "ap-northeast-1", "sa-east-1"]
@GoldieKMG // 명규님 리전 지정이 이상한것 같아요 제가 요청한건: 도쿄, 버지니아, 뭄바이 3곳 입니다;;

2021-09-28 10:37 UTC, GoldieKMG commented on run_create_route53_health_check.py
> +                    "ap-northeast-1", "sa-east-1"]
@yoonjs2 // ap-south-1의 경우 health checker가 존재하지 않습니다 ㅠ ap-southeast-1만 존재합니다
![image](https://user-images.githubusercontent.com/42234701/135071803-eccb0f10-2bcd-4e77-b9c0-b6ec8b05491d.png)

2021-09-28 10:43 UTC, GoldieKMG commented on run_create_route53_health_check.py
> +                    "ap-northeast-1", "sa-east-1"]
@yoonjs2 // 요청주신 region으로 변경 완료했습니다. ap-south-1은 slack으로 말씀드린대로 ap-southeast-2로 하여 진행하겠습니다
![image](https://user-images.githubusercontent.com/42234701/135072467-e4a64fd3-d19e-4b2f-be53-ed0f8a9aa274.png)
![image](https://user-images.githubusercontent.com/42234701/135072507-ccbbbd28-46b6-4310-be71-69d75b5ec1e0.png)

2021-09-28 11:31 UTC, yoonjs2 approved these changes

2021-09-28 11:40 UTC, merged