DEV-14739 전체 저장소에서 node 및 npm 버전 업데이트
HardBoiledSmith/johanna pull request #587
Opened 2022-04-22 12:04 UTC by bjo9280

### What is this PR for?

- node, 14.19.1, npm 6.14.16 버전 업데이트

### How should this be tested?

- vagrant up 동작확인

### Screenshots (if appropriate)
<img width="737" alt="스크린샷 2022-04-22 오후 2 53 08" src="https://user-images.githubusercontent.com/24794855/164710663-7c65b46b-5906-418a-b791-687bd72c6360.png">
<img width="734" alt="Screen Shot 2022-04-22 at 20 59 35 PM" src="https://user-images.githubusercontent.com/24794855/164710682-024be638-cbaa-4c1b-a628-4d1d160b7675.png">

2022-04-28 09:20 UTC, GoldieKMG approved these changes
수정 고맙습니다 👍  provisioning 이상 없이 잘 되는 것 확인했습니다

2022-04-28 12:29 UTC, metocks requested changes
@bjo9280 // nvm도 확인 부탁드립니다 🙏 
- 관련 PR: https://github.com/HardBoiledSmith/hbsmith-web/pull/1099/files
- nvm.sh releases: https://github.com/nvm-sh/nvm/releases

2022-04-29 05:51 UTC, bjo9280 commented
@metocks // nvm업데이트 후 vagrant 동작 확인하였습니다.
<img width="835" alt="Screen Shot 2022-04-29 at 14 46 49 PM" src="https://user-images.githubusercontent.com/24794855/165891119-ec3d1b10-d9a9-45a6-a704-5405f9078d23.png">

2022-04-29 05:52 UTC, singetta reviewed
프로비저닝 node버전 업데이트 감사합니다.

2022-04-29 06:42 UTC, metocks approved these changes
고생하셨습니다!

2022-04-29 07:51 UTC, yoonjs2 approved these changes

2022-05-02 06:09 UTC, merged