DEV-15514 [라미엘] CloudWatch 연동 - johanna, magi 배포 추가
HardBoiledSmith/johanna pull request #610
Opened 2022-08-09 06:20 UTC by metocks

### What is this PR for?

- 라미엘 cloudwatch dashboard 관련 자원과 설정 자동화
- 참조:

### How should this be tested?

- magi의 테스트 진행 참조

2022-08-11 05:06 UTC, singetta requested changes
@metocks // johanna에서 CodeDeploy 지원 및 CloudWatch 연동 기능 추가 감사합니다. 한 가지 궁금한 사항이 있는데요. run_create_ramiel_codedeploy.py는 있는데 run_terminate_ramiel_codedeploy.py는 따로 없어서요. op환경이면 CodeDeploy가 그대로 띄워져있어야 하니 없어도 되겠다 싶은데 qa환경은 테스트 후 모든 인스턴스 제거를 해야하지 않는지요? 별도로 제거하지 않아도 되는지 궁금하네요. 추가로 아래 코드 리뷰 건 확인 부탁드립니다. 🙏🏼

2022-08-11 06:14 UTC, yoonjs2 requested changes
@metocks // 
- https://hbsmith.atlassian.net/browse/DEV-15514?focusedCommentId=92633 에 논의된 내용 반영 감사합니다. :)
- 들여쓰기 잘못된거 수정 부탁드립니다.

2022-08-11 06:14 UTC, yoonjs2 commented on run_create_cloudwatch_dashboard.py
> +    raise Exception()
@metocks // 1수준 들여쓰기 처리 부탁드립니다. 
```suggestion
    if settings['TYPE'] == 'elasticbeanstalk':
        run_create_cw_dashboard_elasticbeanstalk(settings['NAME'], settings)
    elif settings['TYPE'] == 'rds/aurora':
        run_create_cw_dashboard_rds_aurora(settings['NAME'], settings)
    elif settings['TYPE'] == 'sqs,lambda,sms':
        run_create_cw_dashboard_sqs_lambda_sms(settings['NAME'], settings)
    elif settings['TYPE'] == 'alarm':
        run_create_cw_dashboard_alarm(settings['NAME'], settings)
    elif settings['TYPE'] == 'ramiel':
        run_create_cw_dashboard_ramiel(settings['NAME'], settings)
    else:
        print('"%s" is not supported' % settings['TYPE'])
        raise Exception()
```

2022-08-11 06:14 UTC, yoonjs2 commented on run_create_codebuild_default.py
> +        result = aws_cli.run(cmd)
@singetta // 여기서 덮어쓴 result 값은 https://github.com/HardBoiledSmith/johanna/pull/610/files#diff-248c6c6778430c2c15ccdfc8f82decf69769c6907f01cd78251b4fbf91dc437dR105 에서 사용합니다. https://hbsmith.atlassian.net/browse/DEV-15514 이슈로 8/10 스크럼 회의때 논의된 내용입니다.

2022-08-11 06:14 UTC, yoonjs2 commented on run_create_codebuild_default.py
> +        result = aws_cli.run(cmd)
@singetta // 여기서 덮어쓴 result 값은 https://github.com/HardBoiledSmith/johanna/pull/610/files#diff-248c6c6778430c2c15ccdfc8f82decf69769c6907f01cd78251b4fbf91dc437dR105 에서 사용합니다. https://hbsmith.atlassian.net/browse/DEV-15514 이슈로 8/10 스크럼 회의때 논의된 내용입니다.

2022-08-11 06:31 UTC, metocks commented on run_create_codebuild_default.py
> +        result = aws_cli.run(cmd)
답변 감사드립니다 :)

2022-08-11 06:31 UTC, metocks commented on run_create_codebuild_default.py
> +        result = aws_cli.run(cmd)
답변 감사드립니다 :)

2022-08-11 06:38 UTC, metocks commented
> @metocks // johanna에서 CodeDeploy 지원 및 CloudWatch 연동 기능 추가 감사합니다. 한 가지 궁금한 사항이 있는데요. run_create_ramiel_codedeploy.py는 있는데 run_terminate_ramiel_codedeploy.py는 따로 없어서요. op환경이면 CodeDeploy가 그대로 띄워져있어야 하니 없어도 되겠다 싶은데 qa환경은 테스트 후 모든 인스턴스 제거를 해야하지 않는지요? 별도로 제거하지 않아도 되는지 궁금하네요. 추가로 아래 코드 리뷰 건 확인 부탁드립니다. 🙏🏼

@singetta // terminate가 없는 것은 의도적입니다.
billing계정에 있는 codebuild projects가 생성 후 삭제되면 안 되는 것 처럼, codedeploy 자원 역시 마찬가지입니다.
아울러 codedeploy는 billing 계정에서 작동하는 것으로, qa/op 모두 billing계정의 자원을 참조합니다.

2022-08-11 06:41 UTC, metocks commented
> @metocks //
> 
> * https://hbsmith.atlassian.net/browse/DEV-15514?focusedCommentId=92633 에 논의된 내용 반영 감사합니다. :)
> * 들여쓰기 잘못된거 수정 부탁드립니다.

확인 감사합니다. diff 체크가 허술했네요 🙏

2022-08-11 09:13 UTC, singetta commented on run_create_codebuild_default.py
> +        result = aws_cli.run(cmd)
@yoonjs2 // 답변 감사합니다.

2022-08-11 09:13 UTC, singetta commented on run_create_codebuild_default.py
> +        result = aws_cli.run(cmd)
@yoonjs2 // 답변 감사합니다.

2022-08-11 09:15 UTC, singetta commented
> > @metocks // johanna에서 CodeDeploy 지원 및 CloudWatch 연동 기능 추가 감사합니다. 한 가지 궁금한 사항이 있는데요. run_create_ramiel_codedeploy.py는 있는데 run_terminate_ramiel_codedeploy.py는 따로 없어서요. op환경이면 CodeDeploy가 그대로 띄워져있어야 하니 없어도 되겠다 싶은데 qa환경은 테스트 후 모든 인스턴스 제거를 해야하지 않는지요? 별도로 제거하지 않아도 되는지 궁금하네요. 추가로 아래 코드 리뷰 건 확인 부탁드립니다. 🙏🏼
> 
> @singetta // terminate가 없는 것은 의도적입니다. billing계정에 있는 codebuild projects가 생성 후 삭제되면 안 되는 것 처럼, codedeploy 자원 역시 마찬가지입니다. 아울러 codedeploy는 billing 계정에서 작동하는 것으로, qa/op 모두 billing계정의 자원을 참조합니다.

@metocks // 그렇군요. billing계정 자원을 쓰는군요. 답변 감사합니다. :)

2022-08-11 09:15 UTC, singetta approved these changes

2022-08-12 09:26 UTC, GoldieKMG approved these changes
PR 내용 기반으로 정상 세팅 진행되는 부분 확인했습니다 :) 스크럼 미팅에 반영 내용이 상당 있었는데 빠르게 반영해주셨네요 고생하셨습니다 🙏 
<img width="1630" alt="image" src="https://user-images.githubusercontent.com/42234701/184322640-2ec595c7-e2b1-464e-9d18-86522939ff17.png">
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/42234701/184325784-453428b7-88a2-4f48-b75f-59b1e78da83b.png">
실패건은 권한상의 에러로 신경쓰지 않아도 될 부분으로 보여 넘겼습니다.
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/42234701/184325958-519d8c7a-098e-49ee-904e-75b0edec1667.png">

2022-08-16 01:53 UTC, yoonjs2 approved these changes

2022-08-16 01:53 UTC, merged