(PR작성중)DEV-15833 imagebuilder 자동화 johanna코드완료
HardBoiledSmith/johanna pull request #614
Opened 2022-08-25 14:59 UTC by GoldieKMG

### What is this PR for?

- 이 PR이 해결하고자 하는 이슈(JIRA Issue) 및 작업 내용에 대해 설명해 주세요

### How should this be tested?

- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요

### Screenshots (if appropriate)

- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)

2022-08-30 06:04 UTC, GoldieKMG commented on run_terminate_imagebuilder_gendo_old_environment.py
> +        delete_version_list += normal_resource_version_list[2:]
삭제 대상 리스트를 정리 하는 부분입니다.
정상적으로 생성되지 않은 버전의 resouce, 최신 버전 2개 외의 버전

2022-09-01 03:11 UTC, singetta approved these changes
패치 용 이미지 삭제 시 timestamp 비교 후 삭제하도록 구현 하셨네요. 패치 시 termitate_imagebuilder_gendo_old를 상시 실행해줘야 겠네요.
기능 추가 감사합니다. 동작 및 코드 상 이견 없습니다.

2022-09-01 05:58 UTC, yoonjs2 requested changes
@GoldieKMG // 문의사항이 있습니다. 
- 이번 PR에 다음 기능이 포함되어 있을까요?: `DV/QA AWS 계정의 AWS Account 번호를 AMI에 Edit Permission으로 직접 입력하지 않아도 되도록 하는 기능 (AMI Permission에 AWS Account 대신 DV/QA OU값 자동설정)`
  - https://hbsmith.atlassian.net/wiki/spaces/GEN/pages/2392142/Development+Team 
  - https://docs.aws.amazon.com/ko_kr/AWSEC2/latest/UserGuide/share-amis-with-organizations-and-OUs.html
- OP 계정에서 사용중인 AMI 인지 확인하려면 ec2 describe-instances 에서 image-id로 필터걸어서 1개 이상 나오는게 있는지 조회해 보면 될것 같습니다. 여기에 방금 만든 이미지가 사용되기 전 삭제될 경우를 대비하기 위해 생성된지 2개월 이상 지난 이미지(timestamp 기준)만 지우면 어떨까 합니다.
  - https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-instances.html

2022-09-01 05:58 UTC, yoonjs2 commented on run_common.py
> +
@GoldieKMG // 이 함수 아래 위치에도 적용해야 하는게 아닐까요? 혹시 의도적으로 제외하셨나 싶어 문의드립니다.
https://github.com/HardBoiledSmith/johanna/blob/3078f1b5bd72d541db0516e97bf6b71cb7a235b6/run_create_eb_windows.py#L482

2022-09-01 08:44 UTC, metocks approved these changes
고생하셨습니다. 제상님의 리뷰만 반영 부탁드립니다 🙏

2022-09-02 06:40 UTC, GoldieKMG commented
> @GoldieKMG // 문의사항이 있습니다.
> 
> * 이번 PR에 다음 기능이 포함되어 있을까요?: `DV/QA AWS 계정의 AWS Account 번호를 AMI에 Edit Permission으로 직접 입력하지 않아도 되도록 하는 기능 (AMI Permission에 AWS Account 대신 DV/QA OU값 자동설정)`
>   
>   * https://hbsmith.atlassian.net/wiki/spaces/GEN/pages/2392142/Development+Team
>   * https://docs.aws.amazon.com/ko_kr/AWSEC2/latest/UserGuide/share-amis-with-organizations-and-OUs.html
> * OP 계정에서 사용중인 AMI 인지 확인하려면 ec2 describe-instances 에서 image-id로 필터걸어서 1개 이상 나오는게 있는지 조회해 보면 될것 같습니다. 여기에 방금 만든 이미지가 사용되기 전 삭제될 경우를 대비하기 위해 생성된지 2개월 이상 지난 이미지(timestamp 기준)만 지우면 어떨까 합니다.
>   
>   * https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-instances.html

1. DV/QA AWS 계정의 AWS Account 번호를 AMI에 Edit Permission으로 직접 입력하지 않아도 되도록 하는 기능 (AMI Permission에 AWS Account 대신 DV/QA OU값 자동설정)

=> 우선 본 PR에서는 말씀하신 부분 추가되지 않았습니다. terminate 작업 시에 추가 하려고 합니다. (magi에 어떻게 반영할지 고민해서 추가 할 예정) 

<img width="754" alt="image" src="https://user-images.githubusercontent.com/42234701/188072351-8afa8099-e0ac-4813-87e8-98bf5bd7a087.png">
EC2 AMI 탭 -> 해당 AMI 클릭 -> 권한 탭
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/42234701/188073048-1ce6c0b4-6d1a-4488-8fb0-fdd6fa8379d5.png">

2. OP 계정에서 사용중인 AMI 인지 확인하려면 ec2 describe-instances 에서 image-id로 필터걸어서 1개 이상 나오는게 있는지 조회해 보면 될것 같습니다. 여기에 방금 만든 이미지가 사용되기 전 삭제될 경우를 대비하기 위해 생성된지 2개월 이상 지난 이미지(timestamp 기준)만 지우면 어떨까 합니다.

=> 좋은 의견 고맙습니다 2개월이면 어느정도 보장이 될 것 같습니다 :) 1,2번 주신 내용 https://hbsmith.atlassian.net/browse/DEV-16116 이슈에서 차 후 스프린트에 전부 적용 해놓도록 하겠습니다.

2022-09-05 03:25 UTC, yoonjs2 approved these changes

2022-09-05 03:26 UTC, merged