(WIP) DEV-15932 [라미엘] 원클릭배포: codedeploy-full/partial-deployment --> codebuild로 이동
HardBoiledSmith/johanna pull request #621
Opened 2022-09-08 02:48 UTC by metocks

### What is this PR for?

- codedeploy 배포 실행을 codebuild에서 수행
- 참조
    - https://github.com/HardBoiledSmith/magi/pull/941

### How should this be tested?

- magi 동일 배포에서 확인 절차 진행: https://github.com/HardBoiledSmith/magi/pull/941

2022-09-22 03:54 UTC, singetta requested changes
@metocks // 원클릭 배포 코드 추가 감사합니다. 아래 리뷰 확인 부탁드립니다.

2022-09-22 03:54 UTC, singetta commented on run_create_ramiel_full_deployment.py
> +#
test 용으로 OP로 되어 있는데요. 해당 코드 삭제해야 하지 않을까 생각됩니다.

2022-09-22 03:54 UTC, singetta commented on run_create_ramiel_partial_deployment.py
> +    parser.add_option('-t', '--target', help='target on-premises instances which are seperated by semi-colon')
OptionParser여서 아래 [run_common.py](https://github.com/HardBoiledSmith/johanna/blob/45eb4508baa090091c846349d21f0b3a3b09be3e/run_common.py#L527)에 추가해도 -t 인자 값 유무에 따라 동작 할 것 같은데요. parse_args()를 새로 작성하신 이유가 있을까요?

2022-09-22 03:54 UTC, singetta commented on run_create_ramiel_partial_deployment.py
> +#
test 용으로 OP로 되어 있는데요. 해당 코드 삭제해야 하지 않을까 생각됩니다.

2022-09-22 04:10 UTC, metocks commented on run_create_ramiel_partial_deployment.py
> +    parser.add_option('-t', '--target', help='target on-premises instances which are seperated by semi-colon')
@singetta // `-t` 옵션은 라미엘 배포에만 사용하는 옵션이어서 중복을 감안하고 새로 parse_arges()를 만들었습니다.

2022-09-22 04:10 UTC, metocks commented
@singetta // 리뷰 2건을 반영하고 1건에 대한 답변을 게시하였습니다. 확인 부탁드립니다 🙏

2022-09-22 07:13 UTC, singetta commented on run_create_ramiel_partial_deployment.py
> +    parser.add_option('-t', '--target', help='target on-premises instances which are seperated by semi-colon')
@metocks // 답변 감사합니다. johanna가 sachiel, gendo 등 instance에 대한 배포를 관장하고 있는만큼 라미엘에서 사용하는 option도 정규 parse code에 넣는게 좋지 않을까 생각되는데요. @yoonjs2 님 리뷰 의견 받고 수정 여부 결정 부탁드립니다.

2022-09-22 11:35 UTC, GoldieKMG approved these changes
저도 codebuild ci_gendo terminate 하는쪽에 권한 문제가 있더라구요. 그 부분 해결하면서 혹시 알게되는 부분있으면 공유드리겠습니다. 작업 고생하셨습니다 🙏 패치 시 한 군대에서 작업할 수 있어 많이 편해질 것 같습니다

2022-09-23 14:41 UTC, yoonjs2 requested changes

2022-09-23 14:41 UTC, yoonjs2 commented on run_create_ramiel_partial_deployment.py
> +    parser.add_option('-t', '--target', help='target on-premises instances which are seperated by semi-colon')
@metocks // johanna 프로젝트는 초창기부터 아래와 같이 2가지 방식으로 호출있도록 구성되어 있습니다. 예를들어 `run_create_foobar.py` 파일을 만들어 뒀다고 하면 아래와 같이 호출할수 있습니다.
```
방법1: ./run.py create_foobar
방법2: ./run_create_foobar.py
```
관련코드:
https://github.com/HardBoiledSmith/johanna/blob/6b1534afaf6d102fca6dcbc254c93b23a282ba61/run.py#L70-L71
따라서 @metocks 님 구현을 유지할 경우 방법1 로 호출에 문제가 생깁니다. (통일성 깨짐) 그래서 아래와 같이 수정을 요청드립니다.

1. 다른 run_xxxxx와 구현 통일 (아래 코드 참고)
https://github.com/HardBoiledSmith/johanna/blob/fc29b6241118e24e1713208d5f0c955784f9c0f7/run_create_eb.py#L2-L28
2. `-t` 옵션은 옵션이 아닌 args 로 호출 가능하도록 수정 (타겟구분은 띄어쓰기로)
```
방법1: ./run.py create_ramiel_partial_deployment.py HBsmith-0012 HBsmith-0013 ...
방법2: ./run_create_ramiel_partial_deployment.py HBsmith-0012 HBsmith-0013 ...
```

2022-09-23 14:59 UTC, yoonjs2 requested changes
@metocks // 그리고 굳이 2가지 코드로 분리할 필요가 있을까 싶습니다. target 지정 여부로 full deployment 할건지 partial deployment 할건지 정의 가능하지 않을까요? 게다가 둘다 코드가 비슷해서 분리하면 오히려 유지보수 하기 불편할것 같습니다. 그래서 아래와 같이 추가수정 요청드립니다.
```
### AS-IS ###
run_create_ramiel_full_deployment.py
run_create_ramiel_partial_deployment.py

### TO-BE ### (run_create_<AWS서비스이름>_<프로젝트이름> 컨벤션으로)
전체배포: run_create_codedeploy_ramiel.py
일부배포: run_create_codedeploy_ramiel.py HBsmith-0012 HBsmith-0013 ...
```

2022-09-23 23:39 UTC, metocks commented
> @metocks // 그리고 굳이 2가지 코드로 분리할 필요가 있을까 싶습니다. target 지정 여부로 full deployment 할건지 partial deployment 할건지 정의 가능하지 않을까요? 게다가 둘다 코드가 비슷해서 분리하면 오히려 유지보수 하기 불편할것 같습니다. 그래서 아래와 같이 추가수정 요청드립니다.
> 
> ```
> ### AS-IS ###
> run_create_ramiel_full_deployment.py
> run_create_ramiel_partial_deployment.py
> 
> ### TO-BE ### (run_create_<AWS서비스이름>_<프로젝트이름> 컨벤션으로)
> 전체배포: run_create_codedeploy_ramiel.py
> 일부배포: run_create_codedeploy_ramiel.py HBsmith-0012 HBsmith-0013 ...
> ```

@yoonjs2 // 제안해주신 건에 대해, 위의 일부배포처럼 인자를 처리하기 위해서는 AWS codebuild에서 환경변수 설정 덮어쓰기로 받아온 환경변수를 bash에서 나누어야 합니다.
    - 예) https://stackoverflow.com/questions/10520623/how-to-split-one-string-into-multiple-variables-in-bash-shell
혹은 AWS 환경변수를 가변인자처럼 다루는 테크닉이 있을까요? 이에 대한 조언 부탁드립니다 🙏

2022-09-24 05:08 UTC, metocks commented
@singetta @yoonjs2 // 다음 형태로 반영하였습니다.
1. parse_args()를 삭제하고, 공용 parse_args()의 args에 (온프레미스) 인스턴스 목록을 받아옴
2. 온프레미스 인스턴스 목록은 `;`로 구분된 일련의 문자열임. AWS 환경변수에서 가변인수를 처리할 방법을 찾지 못하여 해당 방법 유지
3. partial/full 스크립트를 통합

2022-09-24 15:12 UTC, yoonjs2 commented
> @singetta @yoonjs2 // 다음 형태로 반영하였습니다.
> 
> 1. parse_args()를 삭제하고, 공용 parse_args()의 args에 (온프레미스) 인스턴스 목록을 받아옴
> 2. 온프레미스 인스턴스 목록은 `;`로 구분된 일련의 문자열임. AWS 환경변수에서 가변인수를 처리할 방법을 찾지 못하여 해당 방법 유지
> 3. partial/full 스크립트를 통합

@metocks // 2. 가변인수 처리는 저도 딱히 구분할 방법이 안떠올라서 지금처럼 ;로 구분한 문자열을 받고 이를 파싱하는 식으로 구현하는게 최선일것 같습니다. 1, 3 번 제 의견 반영 감사합니다.

2022-09-24 15:12 UTC, yoonjs2 approved these changes

2022-09-25 23:13 UTC, singetta approved these changes

2022-09-26 04:07 UTC, merged