DEV-16116 (WIP)run_terminate_imagebuilder_gendo.py, run_terminate_imagebuilder_gendo_old_environment.py 스크립트 추가 보완
HardBoiledSmith/johanna pull request #630
Opened 2022-09-29 19:12 UTC by GoldieKMG

### What is this PR for?
- run_terminate_imagebuilder_gendo.py, run_terminate_imagebuilder_gendo_old_environment.py 스크립트 추가 보완

- run_terminate_imagebuilder_gendo.py
    - 기존엔 모든 자원을 종료시켜버렸음. 오로지 gendo_ 에 대한 자원만 삭제하도록변경. 
    - ci_gendo 스크립트와 분리

- run_terminate_imagebuilder_gendo_old_environment.py
    - 8주 이상 된 버전만 삭제하도록 변경
    - 삭제 하기 전 사용하는 이미지의 경우면 삭제 대상에서 제외.
 
### How should this be tested?
- 해당 테스트는 실제 AWS 환경에서 테스트 하는 것으로 시간에 대한 조작이 어렵습니다. 따라서, 위 조건 8주이상 된 버전에 대한 조건을 구성하기에는 너무 많은 시간이 소요 됩니다.
- 삭제가 되는지에 대해 테스트 해보고 싶다면 일시적으로 8주의 시간을(코드라인 코멘트 참조) 1시간 등으로 줄여서 테스트 해볼 수 있습니다.
- 해당 브랜치의 johanna와 magi를 세팅해주세요.
- ./run_create_imagebuilder_gendo.py 를 2회 이상 실행해 주세요.
- 이미지 생성까지 보통 스크립트 실행 후 40~60분정도가 소요됩니다.
- 정상적으로 이미지들이 생성이 되었다면 imagebuilder, ec2 ami snapshot에 정상적으로 자원이 생성되어 있어야 합니다.
- 생성이 되었다면 ./run_terminate_imagebuilder_gendo_old_environment.py 를 실행해주세요.
- 코드를 별도로 건들지 않았다면 생성한 자원들은 삭제되지 않아야 합니다.

사용되고 있는 이미지의 경우는 삭제되지 않도록 하는 코드 테스트)
- 생성한 이미지로 eb gendo를 띄워주세요.
- ./run_create_imagebuilder_gendo.py 를 실행해 주세요.
- 위 스크립트 실행 후 이미지가 생성을 대기해주세요.
- eb gendo에서 사용되는 ami 버전을 기억해주세요.
- ./run_terminate_imagebuilder_gendo_old_environment.py를 실행해주세요.
- 별도로 코드를 건드리지 않았다면 8주가 지나지 않았기 때문에 삭제되지 않아야 합니다.
- 코드로 8주 -> 짧은 시간(1시간)으로 줄인 후 ./run_terminate_imagebuilder_gendo_old_environment.py 를 실행 시킬 경우 eb를 띄울때 사용했던 ami 외 모두 삭제 되어야 합니다.

### Screenshots (if appropriate)

영상 보조 설명
1. 이미지를 4개이상 생성한 상태
2. ./run_terminate_imagebuilder_gendo_old_environment.py 스크립트 실행. -> 8주이상 되지 않았기 때문에 아무것도 삭제되지 않음 
3. 8주에서 2주로 변경 후 실행 -> 실제 생성된 일자가 2주가 지나지 않았기 때문에 아무것도 삭제되지 않음
4. 1주로 변경 후 실행 -> 1주 이상 지난 자원은 전체 삭제. 단, 1주가 지난 자원이더라도 현재 eb에서 사용중인 버전에 대해서는 삭제하지 않음.

https://user-images.githubusercontent.com/42234701/193120952-7a053036-a849-4d1a-8bd6-cc84886c33ed.mov

2022-09-29 19:22 UTC, GoldieKMG commented on run_terminate_imagebuilder_gendo.py
> +        aws_cli.run(cmd, ignore_error=True)
생성된 자원 역순으로 진행하기 위해 위쪽으로 위치 변경함.

2022-09-29 19:22 UTC, GoldieKMG commented on run_terminate_imagebuilder_gendo_old_environment.py
> +                in_use_ec2_ami_list.append(rr['Reservations'][0]['Instances'][0]['ImageId'])
sts role arn을 env로 별도로 뺀 이유는 일반 개인 개발자 계정에서는 arn을 필요로 하지 않습니다. 

개인 개발환경의 경우 빈칸으로 두고 실행시키면 됩니다.

보통 해당 스크립트가 돌아가는 곳은 billing계정인데요, billing 계정에서 OP에 환경에 대해 정보를 알아와야 하기 때문에 sts로 작성했습니다.

2022-10-12 18:07 UTC, GoldieKMG commented on run_terminate_imagebuilder_gendo_old_environment.py
> +            ec2_describe_role_arn = settings['EC2_DESCRIBE_ROLE_ARN']
보통 해당 스크립트가 돌아가는 곳은 billing계정인데요, billing 계정에서 OP에 환경에 대해 정보를 알아와야 하기 때문에 sts로 작성했습니다.

2022-10-13 03:32 UTC, yoonjs2 requested changes

2022-10-13 03:32 UTC, yoonjs2 commented on run_terminate_imagebuilder_gendo_old_environment.py
> +                    in_use_ami_timestamp_version.append(m.group(1))
@GoldieKMG // if 조건문이 단순하다면, 약간 변경하면 들여쓰기를 1~2depth 줄여서 가독성을 높일수 있습니다. 이런 스타일의 작성을 부탁드립니다.
```suggestion
    for img in ec2_gendo_img_list:
        if img['ImageId'] not in in_use_ec2_ami_list:
           continue
        for tag in img['Tags']:
              if tag['Key'] != 'Ec2ImageBuilderArn':
                  continue
              m = re.search('/gendo-recipe-(.+?)/', tag['Value'])
              in_use_ami_timestamp_version.append(m.group(1))
```

2022-10-13 03:32 UTC, yoonjs2 commented on run_terminate_imagebuilder_gendo_old_environment.py
> +            pass
@GoldieKMG // try-catch 는 가급적 1 라인으로 좁히는게 좋습니다. 그리고 안쓸수 있다면 안쓰는게 좋습니다. `re.search()`는 매칭이 실패할 경우 None을 리턴(https://docs.python.org/3/library/re.html#re.search) 하므로 아래와 같이 작성하여 try-catch를 회피 가능합니다.

```suggestion
    for cc in component_list:
        found = re.search('-component-(.+?)/', cc)
        if found:
           timestamp_list.append(found.group(1))
```

2022-10-13 03:32 UTC, yoonjs2 commented on run_create_imagebuilder_gendo.py
> +                "amiTags": {"gendo_git_hash": git_hash_app.decode('utf-8').strip()},
@GoldieKMG // git_hash 포맷은 통일성을 위해 기존 컨벤션을 지켜주세요. 그리고 Tag의 value 값에 hash 정보만 나오게 할수 없나요?
<img width="978" alt="Screen Shot 2022-10-13 at 12 27 33" src="https://user-images.githubusercontent.com/1650254/195492469-0815eec9-82d3-4c81-adc8-1af236164ddc.png">

```suggestion
                "amiTags": {f"git_hash_{name}": git_hash_app.decode('utf-8').strip()},
```

2022-10-13 07:31 UTC, singetta approved these changes
gendo image builder 관리 코드 추가 감사합니다. 항상 PR에 상세 설명 해주신 덕분에 코드가 좀 더 이해하기 쉽네요. 제상님 리뷰 확인만 부탁드립니다.

2022-10-13 08:03 UTC, metocks approved these changes
작업 감사합니다. 제상님의 리뷰 내용만 검토 부탁드립니다 🙏

2022-10-14 08:35 UTC, bjo9280 approved these changes
@GoldieKMG // 고생하셨습니다. 수정된 코드와 의견주신 내용 확인하였습니다.

2022-10-14 10:08 UTC, GoldieKMG commented on run_create_imagebuilder_gendo.py
> +                "amiTags": {"gendo_git_hash": git_hash_app.decode('utf-8').strip()},
@yoonjs2 // 제상님 원하시는 부분대로 나오게 했는데 hash 내용을 변경하기 이전에 작업했던걸로 올라갔습니다 요청주신 부분 그대로 반영될 예정입니다 :) 해시키 작업 전 이미지가 남게 해 혼선드려 죄송합니다.

2022-10-14 10:08 UTC, GoldieKMG commented on run_terminate_imagebuilder_gendo_old_environment.py
> +                    in_use_ami_timestamp_version.append(m.group(1))
@yoonjs2 // 뎁스를 최대한 안나오게 하고 싶었는데 이렇게 풀면 됐었네요 감사합니다 :) 다음 작업 시 참고하겠습니다 👍

2022-10-14 10:08 UTC, GoldieKMG commented on run_terminate_imagebuilder_gendo_old_environment.py
> +            pass
@yoonjs2 // 네 회사 코드 컨벤션에서 말씀해주신대로 try catch는 필요할 때만 사용, 필요할 경우 1줄만 적용하는 부분 리마인드 하겠습니다 🙏

2022-10-17 04:34 UTC, merged