DEV-17437 EB Platform version update
HardBoiledSmith/johanna pull request #660
Opened 2023-01-04 09:46 UTC by GoldieKMG

### What is this PR for?
- EB django, windows 플랫폼 버전 업데이트
https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.python

### How should this be tested?
- AWS 환경 구성 시 EB 인스턴스가 정상적으로 생성 되어야 합니다.

### Screenshots (if appropriate)
<img width="969" alt="image" src="https://user-images.githubusercontent.com/42234701/210527483-64df0dfc-e0b7-466a-91ac-c4bff31c76b0.png">

<img width="957" alt="image" src="https://user-images.githubusercontent.com/42234701/210527654-e7f5c64f-dc54-4aae-b378-f4847dc55a78.png">

2023-01-12 02:47 UTC, metocks approved these changes
EB 플랫폼 업데이트 감사합니다 👍

2023-01-12 04:45 UTC, yoonjs2 requested changes
@GoldieKMG // 본 코드에 이견은 없습니다. 다만 아래 이미지 생성이 실패하는데 확인 부탁드립니다.
 https://ap-northeast-2.console.aws.amazon.com/codesuite/codebuild/591379657681/projects/billing_create_gendo_image/history?region=ap-northeast-2&builds-meta=eyJmIjp7InRleHQiOiIifSwicyI6e30sIm4iOjIwLCJpIjowfQ

2023-01-12 04:50 UTC, GoldieKMG commented
@yoonjs2 // 해당 PR이 master 브랜치에 Merge 되면 해결 되는 부분입니다 🙏 CI Fail을 보게되어 platform 업데이트 진행 했습니다 :) 
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/42234701/211978907-1f3fc382-3ee4-428f-88d7-7926f379ef84.png">

2023-01-12 12:38 UTC, singetta approved these changes
platform update 감사합니다 :)

2023-01-14 10:47 UTC, yoonjs2 approved these changes

2023-01-14 12:43 UTC, merged