(WIP) DEV-17798 Gendo SQS fifo 전환
HardBoiledSmith/johanna pull request #674
Opened 2023-02-20 13:21 UTC by GoldieKMG

### What is this PR for?
- DEV-17798 Gendo SQS fifo 전환

### How should this be tested?

- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요

### Screenshots (if appropriate)

- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)

2023-02-23 03:25 UTC, metocks requested changes
@GoldieKMG // FIFO 적용 감사합니다. 2건 검토 부탁드립니다 🙏

2023-02-23 03:25 UTC, metocks commented on run_create_sqs.py
> +            elapsed_time += 5
@GoldieKMG // 무한 루프에 timeout을 두는 것이 어떨지 제안드립니다 🙏

2023-02-23 03:25 UTC, metocks commented on run_create_sqs.py
> +                    break
@GoldieKMG // depth를 줄이는 것을 제안하여 드립니다 🙏 
```suggestion
            if type(result) == dict and result.get('QueueUrl', None):
                break
```

2023-02-23 06:38 UTC, yoonjs2 commented on run_create_sqs.py
> +            elapsed_time += 5
@GoldieKMG // timeout을 세팅할 경우 standard queue 쪽도 동일하게 로직을 적용하는게 좋을것 같습니다. 그리고 레거시 코드에 굳이 타임아웃을 두지 않았던건 옛날에 queue 생성에 시간이 꽤 걸려서 그랬던걸로 기억합니다.

2023-02-23 06:50 UTC, yoonjs2 commented on run_create_sqs.py
> +        attributes['ContentBasedDeduplication'] = "true"
@GoldieKMG //  `hbsmith_visual_test_result.id` 값으로 직접 deduplication id를 지정하는줄 알았습니다. 근데 `ContentBasedDeduplication`를 선택하신 이유가 궁금합니다. (사실 어떤걸 사용해도 상관없긴 합니다.)

2023-02-23 06:50 UTC, yoonjs2 approved these changes
@GoldieKMG // 저는 코드에 이견은 없는데 궁금한게 있어 문의드렸습니다.

2023-02-24 02:15 UTC, singetta approved these changes
fifo 타입 전환 대응 감사합니다. 코드 및 동작 상 이견 없습니다.
시헌님 리뷰만 확인 부탁드립니다.

2023-02-24 09:06 UTC, GoldieKMG commented on run_create_sqs.py
> +            elapsed_time += 5
@yoonjs2 @metocks // 리뷰 감사합니다. 과거엔 sqs생성 시간도 오래 걸렸었군요 🧐 확인했습니다. 내용 적용하겠습니다.

2023-02-24 10:36 UTC, GoldieKMG commented on run_create_sqs.py
> +        attributes['ContentBasedDeduplication'] = "true"
@yoonjs2 // 초기에 이해하기 위해 중복 관련 옵션을 켜서 만든 후에 테스트를 진행하다보니 베이스가 이렇게 된 것 같습니다.
콘텐츠기반 중복 옵션을 사용하지 않을 경우 제상님이 이야기하신대로 lambda에서 메세지 생성 시에 duplication id를 result id로 지정해주면 될 것 같습니다. 조금 생각해봤을 때 제상님이 이야기하신대로 직접 id를 지정하는게 좋아보입니다. 이 부분 반영 해놓겠습니다 :) 

참고로, 컨텐츠 중복 제거를 활성화 할 경우 duplicationid를 콘텐츠 기반으로 자동으로 생성해서 만듭니다 :)

2023-02-24 10:54 UTC, GoldieKMG commented on run_create_sqs.py
> +        attributes['ContentBasedDeduplication'] = "true"
<img width="1539" alt="image" src="https://user-images.githubusercontent.com/42234701/221160569-b23c3359-7a73-4a9f-89ec-5f6503514688.png">
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/42234701/221160654-eb8d1578-f039-4274-9b2c-fb364f22c86c.png">

id기반으로 중복 정상적으로 제거 되는 분 추가 체크 완료했습니다.

2023-02-26 09:36 UTC, merged