DEV-17858 [FTR] gendo BI 구축 #2 서비스 도입
HardBoiledSmith/johanna pull request #687
Opened 2023-03-27 02:46 UTC by metocks

### What is this PR for?

- gendo 이벤트 사용 현황을 매주 월요일에 메일로 전송
- 참조
    - 

### How should this be tested?

- johanna 동일 PR 테스트 참조

### Screenshots (if appropriate)

- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)

2023-04-06 04:29 UTC, singetta approved these changes
athena 활용 script event 빈도 수 취합 구현 감사합니다. 코드 및 동작 이견 없습니다.

2023-04-06 22:45 UTC, GoldieKMG reviewed
@metocks // BI구축 감사합니다 🙏  2가지 검토 사항이 있어 확인 부탁드리겠습니다

2023-04-06 22:45 UTC, GoldieKMG commented on run.py
> +        __import__('run_create_athena')
@metocks // 두 가지 체크 사항이 있습니다 🙏 
1. if command == 'run_create': 아래 내용은 ./run.py create 명령어가 실행 될 때 실행되는 것들의 집약체인 것으로 기억하고 있습니다. 이 점을 고려하여 해당 내용이 들어간 것인지 문의 드립니다. 다만 create 시 실행되는 부분인지  @yoonjs2 님 더블 체크가 필요할 것 같습니다

2. 아테나의 경우는 생성된 자원 terminate는 시키지 않아도 괜찮을까요? 별도로 terminate에 대한 스크립트는 없는 것으로 보여 남겼습니다

2023-04-07 02:36 UTC, metocks commented on run.py
> +        __import__('run_create_athena')
> @metocks // ci 통과가 안되어있어 master브랜치 내용 해당 브랜치로 merge 및 push 했습니다 :)
> 
> 두 가지 체크 사항이 있습니다 🙏
> 
> 1. if command == 'run_create': 아래 내용은 ./run.py create 명령어가 실행 될 때 실행되는 것들의 집약체인 것으로 기억하고 있습니다. 이 점을 고려하여 해당 내용이 들어간 것인지 문의 드립니다. 다만 create 시 실행되는 부분인지  @yoonjs2 님 더블 체크가 필요할 것 같습니다
> 2. 아테나의 경우는 생성된 자원 terminate는 시키지 않아도 괜찮을까요? 별도로 terminate에 대한 스크립트는 없는 것으로 보여 남겼습니다

@GoldieKMG // 확인 고맙습니다. terminate 로직 추가하였습니다 🙏

2023-04-07 02:42 UTC, metocks commented on run.py
> +        __import__('run_create_athena')
@yoonjs2 // 명규님의 제안 중 1번 항목 검토를 요청드립니다 🙏

2023-04-07 06:46 UTC, GoldieKMG commented on run.py
> +        __import__('run_create_athena')
@metocks // 확인 감사합니다 🙏 제상님 코멘트 여부 주시면 Approve로 돌려놓겠습니다

2023-04-10 02:52 UTC, yoonjs2 requested changes

2023-04-10 02:52 UTC, yoonjs2 commented on run.py
> +        __import__('run_terminate_athena')
@metocks // terminate는 create의 역순이 되어야 의존성 문제를 피할수 있습니다. 148L 위로 이동 부탁드립니다.

2023-04-10 02:52 UTC, yoonjs2 commented on run.py
> +        __import__('run_create_athena')
@metocks @GoldieKMG //  첨엔 분석용이니 run_create.py 등에 포함시킬 생각은 안했는데요. 생각해보니 원칙상 프로비저닝이 되야 하는게 맞고 자원이 살아있으면 계속 돈이 나가니 현재처럼 포함시켜 주는게 맞을것 같습니다.

2023-04-10 02:52 UTC, yoonjs2 commented on run.py
> +        __import__('run_create_athena')
@metocks // 알람이나 대시보드는 리소스 생성이 끝나고 마지막에 설정하는 식이니 run_create_athena 는 135L과 136L 사이에 오는게 맞을것 같습니다.

2023-04-10 05:34 UTC, metocks commented
@yoonjs2 // run_terminate_athena 추가 및 create/terminate 위치를 수정하였습니다.

2023-04-10 07:10 UTC, yoonjs2 approved these changes

2023-04-10 07:10 UTC, merged