DEV-18133 naoko,gendo 제외한 모든 arm64 지원 vagrant에서 awslinux2 프로비저닝 코드 삭제 (arm64 fedora 프로비저닝 코드만 남김)
HardBoiledSmith/johanna pull request #701
Opened 2023-04-20 07:34 UTC by metocks

### What is this PR for?

- al2 프로비저닝 코드 삭제

### How should this be tested?

- vagrant up 성공
- ssh로 dv-johanna.hbsmith.io 접속 성공
- 참조
    - ㅁ
    - ㅁ
    - ㅁ
    - ㅁ
    - ㅁ
    - ㅁ

2023-04-27 10:22 UTC, GoldieKMG approved these changes
작업 감사합니다. x86 프로비저닝 코드 제거  된 부분 확인했습니다 🙏

2023-04-27 13:56 UTC, yoonjs2 requested changes
@metocks // 아래 코드도 지워주세요
https://github.com/HardBoiledSmith/johanna/pull/701/files#diff-3c2c558f0e00e35244767f2634800cb7a946614f1b616ad9d27aa68fb5d1f93cR15-R19

2023-04-28 01:57 UTC, metocks commented
> @metocks // 아래 코드도 지워주세요 https://github.com/HardBoiledSmith/johanna/pull/701/files#diff-3c2c558f0e00e35244767f2634800cb7a946614f1b616ad9d27aa68fb5d1f93cR15-R19

@yoonjs2 // 반영하였습니다.

2023-04-29 01:43 UTC, yoonjs2 approved these changes

2023-04-29 01:43 UTC, merged