(WIP) DEV-19042 [라미엘] Route53 health checker 민감도 조정
HardBoiledSmith/johanna pull request #728
Opened 2023-08-10 09:05 UTC by metocks

### What is this PR for?

- 이 PR이 해결하고자 하는 이슈(JIRA Issue) 및 작업 내용에 대해 설명해 주세요

### How should this be tested?

- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요

### Screenshots (if appropriate)

- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)

2023-08-10 10:03 UTC, metocks commented
@yoonjs2 @GoldieKMG // op패치 때 다음 절차로 health check를 재배포 해야합니다:


기존 라미엘의 route53 health check 부분 삭제: ./run_terminate_route53_health_check.py ramiel -f
신규 라미엘의 route53 health check 부분 배포: ./run_create_route53_health_check.py ramiel -f

2023-08-17 02:51 UTC, singetta requested changes
@metocks // Route53 health checker 민감도 확인 추가 감사합니다. 아래 코드 질문이 있는데요. 확인 부탁드립니다.

2023-08-17 02:51 UTC, singetta commented on run_create_route53_health_check.py
> +
full deployment 시 target_name=None으로 name과 다른데요. 해당 로직으로는 return되어 생성되지 않는것 아닌지요?

2023-08-17 02:51 UTC, singetta commented on run_terminate_route53_health_check.py
> +
full deployment 시 target_name=None으로 name과 다른데요. 해당 로직으로는 return되어 삭제되지 않는것 아닌지요?

2023-08-17 03:39 UTC, GoldieKMG requested changes
반영 감사합니다 🙏  확인했으면 하는 부분이 있어 코멘트 남겼습니다

2023-08-17 03:39 UTC, GoldieKMG commented on run_terminate_route53_health_check.py
> +        delete_route53_health_check(settings, target_name)
타 스크립트 처럼 타겟을 지정할 수 있게 지원하려면 동일한 구조로 가는건 어떨까요?
현재 구조라면 여러 번의 delete_route53_health_check 의 함수가 호출 될 것 같습니다.
추가적으로 아래 조건으로 인해 full deployment는 불가해질 것 같습니다 
```
if name != target_name:
    return;
```

아래 처럼 기존 특정 target을 지정하는 코드 구조로 개선하는건 어떨까요?
아래는 예시 코드입니다 :) 실제 돌려본 코드가 아니며, 추가적으로 보완해야 할 코드가 있습니다 🙏 
```
target_name = None
is_target_exists = False

if len(args) > 1:
    target_name = args[1]

for settings in env.get('route53', list()):
    if target_name and settings['NAME'] != target_name:
        continue

    is_target_exists = True
    delete_route53_health_check(settings, target_name)
```

외적으로 target 지정 후 조건에 맞지 않으 그냥 return 되었을 경우 매칭되는 값이 없다는 내용의 alert가 있으면 좋을 것 같습니다

2023-08-17 03:39 UTC, GoldieKMG commented on run_create_route53_health_check.py
> +        create_route53_health_check(settings, target_name)
타 스크립트 처럼 타겟을 지정할 수 있게 지원하려면 동일한 구조로 가는건 어떨까요?
현재 구조라면 여러 번의 delete_route53_health_check 의 함수가 호출 될 것 같습니다.
추가적으로 아래 조건으로 인해 full deployment는 불가해질 것 같습니다
```
if name != target_name:
    return;
```
아래 처럼 기존 특정 target을 지정하는 코드 구조로 개선하는건 어떨까요?
```
target_name = None
is_target_exists = False

if len(args) > 1:
    target_name = args[1]

for settings in env.get('route53', list()):
    if target_name and settings['NAME'] != target_name:
        continue

    is_target_exists = True
    create_route53_health_check(settings, target_name)
```
외적으로 target 지정 후 조건에 맞지 않으 그냥 return 되었을 경우 매칭되는 값이 없다는 내용의 alert가 있으면 좋을 것 같습니다

2023-08-21 05:32 UTC, metocks commented on run_create_route53_health_check.py
> +
@singetta // 조언 감사드립니댜. 버그가 맞아 수정하였습니다 👍

2023-08-21 05:51 UTC, metocks commented on run_create_route53_health_check.py
> +        create_route53_health_check(settings, target_name)
@GoldieKMG // 리뷰 반영하였습니다. 제안 감사드리니다 👍

2023-08-21 05:54 UTC, metocks commented on run_terminate_route53_health_check.py
> +        delete_route53_health_check(settings, target_name)
@GoldieKMG // 반영하였습니다. 리뷰 감사합니다. 👍

2023-08-21 05:54 UTC, metocks commented on run_terminate_route53_health_check.py
> +
@GoldieKMG // 반영하였습니다. 리뷰 감사합니다. 👍

2023-08-21 06:20 UTC, yoonjs2 approved these changes

2023-08-21 06:20 UTC, merged