DEV-19640 eb gendo platform version update 2.11.8 -> 2.12.0
HardBoiledSmith/johanna pull request #741
Opened 2023-10-24 08:39 UTC by GoldieKMG

### What is this PR for?

- DEV-19640 eb gendo platform version update 2.11.8 -> 2.12.0

2023-10-25 23:34 UTC, metocks approved these changes
플랫폼 버전업 감사합니다 👍

2023-10-26 02:38 UTC, singetta approved these changes

2023-10-26 08:08 UTC, yoonjs2 requested changes
@GoldieKMG // python platform도 업그레이드 부탁드립니다.
`64bit Amazon Linux 2 v3.5.8 running Python 3.8`

2023-10-26 09:47 UTC, GoldieKMG commented
@yoonjs2 // 리뷰 감사합니다. 리뷰 주신대로 문서에 python도 버전 업 되어있는 부분 확인 하여 반영 해놓겠습니다

2023-10-30 01:03 UTC, yoonjs2 approved these changes

2023-10-30 01:04 UTC, merged