DEV-21087 [johanna] VPC 네트워크 보안 강화
HardBoiledSmith/johanna pull request #802
Opened 2024-05-27 10:55 UTC by metocks

### What is this PR for?

- network acl로 ssh, rdp 포트 차단

### How should this be tested?

- DEV-21087로 johanna 배포
- ./run_create_vpc -f;
- ACL 확인

### Screenshots (if appropriate)

![image](https://github.com/HardBoiledSmith/johanna/assets/12525941/074d3acb-2b91-4e00-afce-7eb5092ecd51)

2024-05-30 04:17 UTC, singetta approved these changes
vpc 네트워크 보안 강화 코드 확인하였습니다. 코드 상 특별히 이상한 부분은 보이지 않네요. 구현 감사합니다.

2024-05-30 17:05 UTC, yoonjs2 requested changes
@metocks // 시헌님, 우리가 생성한 VPC가 아닌 AWS에서 기본으로 생성한 VPC와 이 VPC에 연결된 SG, ACL에 대해서도 보안강화 처리 가능할까요? 우리가 생성한 EB, RDS VPC의 SG, ACL에 대해선 처리 하신건 확인 했습니다.

2024-05-31 02:00 UTC, metocks commented
> 생성한 VPC가 아닌 AWS에서 기본으로 생성한



> @metocks // 시헌님, 우리가 생성한 VPC가 아닌 AWS에서 기본으로 생성한 VPC와 이 VPC에 연결된 SG, ACL에 대해서도 보안강화 처리 가능할까요? 우리가 생성한 EB, RDS VPC의 SG, ACL에 대해선 처리 하신건 확인 했습니다.

@yoonjs2 // 기본으로 생성한 VPC와 이 VPC에 연결된 SG, ACL에 대해서도 보안강화 처리 수행하였습니다
- default network acl에 ssh, rdp 막기
- default sg rules 삭제

2024-05-31 03:00 UTC, GoldieKMG approved these changes
내용 확인했습니다 수정 고생하셨습니다 🙏

2024-06-03 03:05 UTC, yoonjs2 approved these changes

2024-06-03 03:05 UTC, merged