DEV-20898 [라미엘] TURN서버 EB화 #2
HardBoiledSmith/johanna pull request #803
Opened 2024-05-29 11:17 UTC by metocks

### What is this PR for?

- 이 PR이 해결하고자 하는 이슈(JIRA Issue) 및 작업 내용에 대해 설명해 주세요

### How should this be tested?

- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요

### Screenshots (if appropriate)

- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)

2024-05-30 04:28 UTC, singetta approved these changes
turn서버 EB화 코드 확인하였습니다. 코드 상 이견 없습니다. 추가 감사합니다.

2024-05-31 03:15 UTC, GoldieKMG approved these changes
op환경만 생성 가능하도록 코드로 막은 후, 생성 중간중간 단계에서 DNS체크등 코드 살펴보았습니다. 작업 고생하셨습니다 이견 없습니다 🙏

2024-06-03 06:13 UTC, yoonjs2 requested changes
@metocks // conflict 수정 해결 부탁드립니다.

2024-06-03 06:31 UTC, metocks commented
> @metocks // conflict 수정 해결 부탁드립니다.

처리하였습니다 🙏

2024-06-03 07:42 UTC, yoonjs2 approved these changes

2024-06-03 07:42 UTC, merged