DEV-21236 elastic beanstalk, imagebuilder window image version update
HardBoiledSmith/johanna pull request #804
Opened 2024-05-30 01:14 UTC by GoldieKMG

### What is this PR for?

- elastic beanstalk, imagebuilder window image version update

### How should this be tested?
- windows 이미지를 사용하는 imagebuilder 및 EB 생성 시 문제없이 되어야 합니다.

### Screenshots (if appropriate)
https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.net

<img width="986" alt="image" src="https://github.com/HardBoiledSmith/johanna/assets/42234701/7ca0d803-2442-46fa-9acb-162d908376fc">

2024-05-30 04:35 UTC, singetta approved these changes

2024-05-30 16:26 UTC, yoonjs2 requested changes

2024-05-30 16:26 UTC, yoonjs2 commented on run_create_lambda_cron.py
> +            aws_cli.run(cmd)
@GoldieKMG // DEV-21236 과 관련이 없어 보입니다. 확인 부탁드립니다.
```suggestion
```

2024-05-30 16:26 UTC, yoonjs2 commented on run_create_lambda_cron.py
> +        aws_cli.run(cmd)
@GoldieKMG // DEV-21236 과 관련이 없어 보입니다. 확인 부탁드립니다.

2024-05-31 03:44 UTC, GoldieKMG commented on run_create_lambda_cron.py
> +            aws_cli.run(cmd)
@yoonjs2 // 리뷰 감사합니다 🙏  이전에 slack_slow 이슈 작업하면서 발견된 버그의 코드를 보강한 부분으로서 타 이슈에서 추가작업을 해야하는 부분은 맞습니다.
해당 코드 원복 및 다른 이슈로 작성하여 올리도록 하겠습니다

2024-05-31 03:44 UTC, GoldieKMG commented on run_create_lambda_cron.py
> +        aws_cli.run(cmd)
@yoonjs2 // 리뷰 감사합니다 🙏  이전에 slack_slow 이슈 작업하면서 발견된 버그의 코드를 보강한 부분으로서 타 이슈에서 추가작업을 해야하는 부분은 맞습니다.
해당 코드 원복 및 다른 이슈로 작성하여 올리도록 하겠습니다

2024-05-31 03:50 UTC, GoldieKMG commented on run_create_lambda_cron.py
> +            aws_cli.run(cmd)
https://github.com/HardBoiledSmith/johanna/pull/805 이슈로 작성하여 올렸습니다.

2024-05-31 03:50 UTC, GoldieKMG commented on run_create_lambda_cron.py
> +        aws_cli.run(cmd)
https://github.com/HardBoiledSmith/johanna/pull/805 이슈로 작성하여 올렸습니다.

2024-06-03 03:03 UTC, merged