DEV-21033 [kaji] Dashboard 추가
HardBoiledSmith/johanna pull request #839
Opened 2024-07-24 09:18 UTC by GoldieKMG

### What is this PR for?

- 이 PR이 해결하고자 하는 이슈(JIRA Issue) 및 작업 내용에 대해 설명해 주세요

### How should this be tested?

- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요

### Screenshots (if appropriate)

- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)

2024-08-01 02:26 UTC, singetta approved these changes
johanna에서  django 코드 추가 확인하였습니다. 구현 감사합니다.

2024-08-02 01:49 UTC, metocks requested changes
@GoldieKMG // sachiel, nerv에 영향이 있을지 문의드립니다 🙏

2024-08-02 07:09 UTC, yoonjs2 commented
> @GoldieKMG // sachiel, nerv에 영향이 있을지 문의드립니다 🙏

@metocks // 제 생각엔 기존의 환경변수와 겹치지 않기 때문에 문제가 없을것 같습니다.

2024-08-02 07:09 UTC, yoonjs2 approved these changes
@GoldieKMG // 추가 감사합니다. 좀더 시각적으로 확인이 가능하겠네요.

2024-08-05 03:29 UTC, GoldieKMG commented
@metocks // 리뷰 감사합니다. 전체환경을 띄워 확인한 부분은 아니지만 기존 환경에서 해당 환경변수를 사용한 적이 없기 떄문에 영향은 없을 것으로 생각 됩니다.

2024-08-05 04:30 UTC, merged